/* ============================================================
   js/catinfo.js — 用語ビュー用のカテゴリとやや詳しい解説
   キーは用語（glossary の term）の小文字。新しい用語はここに1行追加する。
   未登録の用語は「その他」として表示される（scripts/check.mjs が警告を出す）。
   ============================================================ */

/* ===== 用語カテゴリ＆やや詳しい解説（用語ビュー用。tooltipは各論文glossaryの簡潔descを使用） ===== */
const CAT_ORDER=["細胞・組織","遺伝子・タンパク質","シグナル・経路","代謝・分子","プロセス・現象","手法・モデル","疾患・病態"];
const CATINFO={
  "leads":{cat:"手法・モデル",long:"hiPSC由来の肝細胞・HSC・LSEC・KCを側流路つきマイクロ流体チップに配置したMASHモデル。Yu Hanryグループによる。"},
  "resmetirom":{cat:"代謝・分子",long:"肝選択的な甲状腺ホルモン受容体βアゴニストで、MASHに対して承認された薬剤。モデルの薬剤応答評価に用いられる。"},
  "vehicle":{cat:"手法・モデル",long:"薬剤や脂質を溶かす溶媒だけを与える対照。溶媒自体の効果を切り分けるために必須で、これを欠くと交絡が見えなくなる。"},
  "smfish":{cat:"手法・モデル",long:"single-molecule fluorescence in situ hybridization。個々のmRNA分子を組織切片上で数える手法で、位置情報を保ったまま定量できる。"},
  "periportal":{cat:"細胞・組織",long:"門脈周囲（zone 1）。酸素が高く、糖新生やアンモニア処理が優位な領域。"},
  "pericentral":{cat:"細胞・組織",long:"中心静脈周囲（zone 3）。酸素が低く解糖や薬物代謝が優位で、同時にWntのソースでもあるため酸素とWntが交絡する。"},
  "landmark gene":{cat:"手法・モデル",long:"ゾーン依存性が既知で、単一細胞の小葉座標を推定する基準として使われる遺伝子。"},
  "lobule":{cat:"細胞・組織",long:"肝小葉。肝の構造単位で、六角形の頂点に門脈域、中心に中心静脈を持つ。"},
  "taz":{cat:"遺伝子・タンパク質",long:"transcriptional coactivator with PDZ-binding motif。Hippo経路のエフェクターで、NASH肝細胞で上昇しTEADと組んでIhhを誘導し線維化を駆動する。"},
  "wwtr1":{cat:"遺伝子・タンパク質",long:"WW domain containing transcription regulator 1。TAZをコードする遺伝子名で、発現量を測る際はこちらの名称を用いる。"},
  "tead":{cat:"遺伝子・タンパク質",long:"TEA domain transcription factor。TAZやYAPと複合体を形成してDNAに結合し、標的遺伝子の転写を起動する。"},
  "ihh":{cat:"遺伝子・タンパク質",long:"Indian hedgehog。TAZ/TEADが誘導する分泌因子で、肝細胞から肝星細胞へ線維化シグナルを渡すパラクリンの担い手。"},
  "paa":{cat:"代謝・分子",long:"phenylacetic acid（フェニル酢酸）。芳香族アミノ酸の微生物代謝産物で、慢性投与により脂肪化とBCAA代謝の変化を誘導する。日本では覚醒剤原料に該当し取扱いに指定が要る。"},
  "bcaa":{cat:"代謝・分子",long:"branched-chain amino acid（分岐鎖アミノ酸）。ロイシン・イソロイシン・バリンを指し、脂肪化に伴って血中濃度が上昇し代謝が脱制御される。"},
  "metagenomics":{cat:"手法・モデル",long:"便などの試料に含まれる全微生物ゲノムを網羅的に配列決定し、菌叢の構成と機能ポテンシャルを推定する手法。"},
  "gene richness":{cat:"プロセス・現象",long:"腸内細菌叢が保有する遺伝子の多様度。低richnessは肥満・インスリン抵抗性・脂肪化と結びつく。"},
  "fmt":{cat:"手法・モデル",long:"fecal microbiota transplantation（糞便微生物叢移植）。菌叢の因果的寄与を検証するための介入手段。"},
  "proteobacteria":{cat:"細胞・組織",long:"LPSを産生するグラム陰性菌を多く含む細菌門。脂肪化を伴う患者の腸内で優位になりエンドトキシン供給源となる。"},
  "high-resolution respirometry":{cat:"手法・モデル",long:"酸素電極を用いて単離ミトコンドリアや透過処理組織の酸素消費を高感度に測定する手法。基質と阻害剤を順に加えて呼吸の各成分を分解できる。"},
  "maximal respiration":{cat:"プロセス・現象",long:"基質を飽和させ脱共役剤を加えたときに到達する最大の酸素消費速度。ミトコンドリアの「質」を量と切り離して評価する指標になる。"},
  "uncoupling":{cat:"プロセス・現象",long:"電子伝達とATP合成の共役が外れ、プロトン勾配が熱として散逸する状態。NASH肝ではリークとともに増加し正味の呼吸効率を下げる。"},
  "8-ohdg":{cat:"代謝・分子",long:"8-hydroxy-2'-deoxyguanosine。酸化的DNA損傷の代表的マーカーで、NASH肝では抗酸化能の低下と並行して増加する。"},
  "nafl":{cat:"疾患・病態",long:"non-alcoholic fatty liver。炎症や線維化を伴わない単純性脂肪肝の段階で、この段階ではミトコンドリア呼吸がむしろ亢進している。"},
  "hepatic mitochondrial flexibility":{cat:"プロセス・現象",long:"過栄養とインスリン抵抗性の初期に肝が呼吸能を押し上げる適応。NASHで失われるため、呼吸速度が非単調に変化する原因となる。"},
  "ffa":{cat:"代謝・分子",long:"free fatty acid（遊離脂肪酸）。培地に加えて肝細胞に脂肪滴を蓄積させる基本入力で、飽和/不飽和の比によって毒性が大きく変わる。"},
  "oa":{cat:"代謝・分子",long:"oleic acid（オレイン酸、C18:1）。一価不飽和脂肪酸で脂肪滴に取り込まれやすく、単独では毒性が低いためパルミチン酸の傷害を緩和する。"},
  "pa":{cat:"代謝・分子",long:"palmitic acid（パルミチン酸、C16:0）。飽和脂肪酸で小胞体ストレスとアポトーシスを誘導しやすく、脂肪肝モデルにおける傷害側の主因となる。"},
  "benign chronic steatosis":{cat:"疾患・病態",long:"傷害や炎症を伴わない慢性的な脂肪蓄積の段階。OA:PA=2:1条件が模す病態で、線維化が点火しないのはこの段階の性質による。"},
  "ntf3":{cat:"遺伝子・タンパク質",long:"neurotrophin-3。神経栄養因子ファミリーの分泌リガンド。進行期NASHで活性化HSCが分泌し、自己の受容体NTRK3(TrkC)に自己分泌的に結合してHSC活性化を維持する。"},
  "ntrk3":{cat:"遺伝子・タンパク質",long:"neurotrophic receptor tyrosine kinase 3。TrkCをコードする受容体型チロシンキナーゼで、NTF3の受容体。進行期HSCで自己分泌回路の中核となり、薬理学的阻害でマウスNASH線維化が退縮した治療標的。"},
  "trkc":{cat:"遺伝子・タンパク質",long:"tropomyosin receptor kinase C（NTRK3がコード）。HSC膜上でNTF3を受け取り活性化シグナルを伝える受容体タンパク。NTRK2(TrkB)と同じTrk受容体ファミリー。"},
  "autocrine":{cat:"プロセス・現象",long:"自己分泌。細胞が分泌した因子が同じ細胞自身の受容体に作用するシグナル様式。進行期HSCではNTF3→NTRK3の自己分泌ループが活性化を自己維持し線維化を駆動する。"},
  "nash":{cat:"疾患・病態",long:"non-alcoholic steatohepatitis（非アルコール性脂肪肝炎、現在はMASHに改称）。脂肪化に炎症・肝細胞傷害・線維化を伴う段階で、進行期線維化が肝関連予後を左右する。"},
  "3d mlho":{cat:"手法・モデル",long:"three-dimensional multi-lineage hepatic organoid。hESC由来の5細胞種（肝細胞・胆管細胞・HSC・内皮・Kupffer細胞）を肝に近い比率（HEP60％・他10％ずつ）でPEG/PDMS低接着上に集合させた三次元肝オルガノイド。肝細胞単独培養よりヒト肝に近い転写・代謝・免疫応答を示し間接的肝毒性のモデルになる。"},
  "hesc":{cat:"細胞・組織",long:"human embryonic stem cell（ヒト胚性幹細胞）。段階的分化により肝の5細胞種を作り出す出発材料。"},
  "heps":{cat:"細胞・組織",long:"hepatocytes（肝細胞）。ALB/CYP3A4を発現する肝実質細胞で3D MLHOの約60％を占める主要細胞。"},
  "cho":{cat:"細胞・組織",long:"cholangiocytes（胆管細胞）。CK19/SOX9/HNF6陽性で胆管様管腔を形成する非実質細胞。"},
  "imp":{cat:"手法・モデル",long:"imipramine（イミプラミン）。三環系抗うつ薬。肝細胞単独では無毒だが3D MLHOでのみ強い毒性を示し、本論文の間接的肝毒性の主役となった薬剤。"},
  "trkb":{cat:"遺伝子・タンパク質",long:"tropomyosin receptor kinase B（NTRK2がコード）。神経栄養因子受容体チロシンキナーゼで、HSCに高発現しimipramineが直接結合する間接的肝毒性の起点受容体。"},
  "ntrk2":{cat:"遺伝子・タンパク質",long:"neurotrophic receptor tyrosine kinase 2。TrkBをコードする遺伝子で、scRNA-seqでHSCに最も高発現する。"},
  "p53":{cat:"遺伝子・タンパク質",long:"tumor protein p53（TP53）。ストレス応答・腫瘍抑制の転写因子で、IMP–TrkB下流のHSCで上昇しmiR-34a-3p産生を促す。"},
  "hnrnpa2b1":{cat:"遺伝子・タンパク質",long:"heterogeneous nuclear ribonucleoprotein A2/B1。miRNAをエクソソームへ選別的に積み込むRNA結合タンパクで、IMPで上昇する。"},
  "dgcr8":{cat:"遺伝子・タンパク質",long:"DiGeorge syndrome critical region 8。miRNAプロセシング（Microprocessor複合体）構成因子で、IMPで上昇しmiR-34a-3p産生を支える。"},
  "mir-34a-3p":{cat:"遺伝子・タンパク質",long:"microRNA-34a-3p。p53応答性miRNAで、毒性エクソソームに選択的に濃縮され肝細胞でXIAPを抑制してアポトーシスを誘導する細胞間伝令分子。"},
  "xiap":{cat:"遺伝子・タンパク質",long:"X-linked inhibitor of apoptosis protein。抗アポトーシスタンパクでmiR-34a-3pの直接標的。抑制されるとcaspase3が活性化し肝細胞がアポトーシスする。"},
  "caspase3":{cat:"シグナル・経路",long:"cysteine-aspartic protease 3。アポトーシス実行カスパーゼで、XIAP低下により活性化して肝細胞死を実行する（cleaved caspase3で検出）。"},
  "exosome":{cat:"代謝・分子",long:"径100〜150 nmの細胞外小胞（toxic-EXOs）。miRNA等を運ぶ細胞間伝令で、IMP下では積荷がmiR-34a-3pに偏って『毒性エクソソーム』化する（総量・サイズは不変）。"},
  "gw4869":{cat:"手法・モデル",long:"中性スフィンゴミエリナーゼ阻害薬。エクソソーム生合成を遮断し、IMPの間接的肝毒性を軽減するネガコン操作に用いられた。"},
  "antagomir-34":{cat:"手法・モデル",long:"miR-34を中和する化学修飾アンチセンス（antagomir）。in vivoでIMP肝障害を軽減し、miR-34a-3p依存性を裏づけた。"},
  "nta":{cat:"手法・モデル",long:"nanoparticle tracking analysis（ナノ粒子トラッキング解析）。エクソソームの濃度・粒径分布を計測する手法。"},
  "scrank":{cat:"手法・モデル",long:"単一細胞解像度で薬剤–標的摂動をシミュレートし最も応答する細胞集団を順位づけるin silico手法。本論文でHSCをTrkB摂動の最応答性細胞と予測した。"},
  "celltiter-glo":{cat:"手法・モデル",long:"ATP量から細胞生存率を定量する発光アッセイ。58薬剤スクリーニングの毒性判定に用いた。"},
  "cmax":{cat:"代謝・分子",long:"maximum plasma concentration（最高血漿中濃度）。薬剤を臨床曝露に近い用量で試験するための基準濃度。"},
  "osm":{cat:"シグナル・経路",long:"Oncostatin M。肝細胞成熟を促すサイトカインで、HGF・デキサメタゾンと併用してHEP分化に用いた。"},
  "cyp3a4":{cat:"遺伝子・タンパク質",long:"cytochrome P450 3A4。主要な薬物代謝酵素で、3D MLHOで2D比約6倍の活性を示し肝機能成熟の指標となった。"},
  "ngfr":{cat:"遺伝子・タンパク質",long:"nerve growth factor receptor（p75）。HSC特異的表面マーカーで分化HSCの同定に用いた。"},
  "pdgfr-β":{cat:"遺伝子・タンパク質",long:"platelet-derived growth factor receptor beta。HSC/ペリサイトのマーカー受容体で分化HSCの同定に用いた。"},
  "desmin":{cat:"遺伝子・タンパク質",long:"desmin（デスミン）。中間径フィラメントでHSCの細胞骨格マーカー。分化HSCの同定に用いた。"},
  "cd9":{cat:"遺伝子・タンパク質",long:"cluster of differentiation 9（テトラスパニン）。エクソソーム表面マーカーで、抗体で取り込みを阻害でき毒性エクソソームの肝細胞取り込みを担う。"},
  "tsg101":{cat:"遺伝子・タンパク質",long:"tumor susceptibility gene 101。多胞体由来エクソソームのマーカータンパクで、単離エクソソームの同定に用いた。"},
  "shgs":{cat:"手法・モデル",long:"老化肝細胞遺伝子シグネチャ（senescent hepatocyte gene signature）。in vitro/in vivoの肝細胞老化モデルから定義された遺伝子セットで、複数マウスモデルと大規模ヒトコホートでMASLDの進行・退縮に一致して変動する、老化肝細胞バーデンの読み出し指標。"},
  "senolytic":{cat:"手法・モデル",long:"老化細胞を選択的に除去する薬剤の総称（セノリティック）。全身性老化向け（dasatinib+quercetin等）はマウスMASLDで効果が乏しく、本論文は肝細胞老化に効くDpCを化合物スクリーニングで同定した。"},
  "dpc":{cat:"手法・モデル",long:"di-2-pyridylketone 4-cyclohexyl-4-methyl-3-thiosemicarbazone。約2,100化合物のスクリーニングで同定された、非老化細胞を傷つけずSHGS+肝細胞を選択的に殺すセノリティックで、雄マウスでMASLD（脂肪化・炎症・線維化・細胞死）を改善する。"},
  "gdf15":{cat:"遺伝子・タンパク質",long:"growth differentiation factor 15。老化肝細胞が分泌するSASP因子で、血中濃度がSHGS量・疾患進行と並行して上昇する非破壊的バイオマーカー。近傍細胞のTGFBR2を介して病態悪化に寄与する。"},
  "tgfbr2":{cat:"遺伝子・タンパク質",long:"TGF-β受容体2型（TGF-β receptor type 2）。TGF-βスーパーファミリー受容体で、老化肝細胞由来GDF15の作用点として近傍細胞で疾患進行を媒介する。"},
  "p21":{cat:"遺伝子・タンパク質",long:"サイクリン依存性キナーゼ阻害因子1A（CDKN1A）。細胞周期停止を担い、SHGS+老化肝細胞はp21+細胞に由来する。"},
  "sasp":{cat:"プロセス・現象",long:"老化関連分泌表現型（senescence-associated secretory phenotype）。老化細胞が放出する炎症・線維化促進性の分泌因子群で、GDF15などを含み周囲組織の病態を駆動する。"},
  "sa-β-gal":{cat:"手法・モデル",long:"老化関連β-ガラクトシダーゼ（senescence-associated β-galactosidase）。細胞老化の代表的染色マーカーで、パルボシクリブ誘導の老化肝細胞でほぼ100%陽性となる。"},
  "palbociclib":{cat:"手法・モデル",long:"CDK4/6阻害薬（PD-0332991）。肝細胞に強固で不可逆的な細胞周期停止＝老化を誘導し、本論文ではSHGS構築の老化モデルに用いられた。"},
  "cdk4/6":{cat:"シグナル・経路",long:"サイクリン依存性キナーゼ4/6。細胞周期のG1/S移行を駆動し、阻害すると細胞周期が停止して細胞老化が誘導される。"},
  "cellular senescence":{cat:"プロセス・現象",long:"ストレス等で誘導される不可逆的な細胞周期停止状態。SASPを伴って周囲組織に影響し、MASLDでは老化肝細胞の蓄積が病態進行と関連する。"},
  "huh7":{cat:"細胞・組織",long:"ヒト肝がん由来株化細胞（Huh7）。パルボシクリブ処理で強固な老化表現型を示し、SHGS構築の老化モデルに使用された。"},
  "tim4":{cat:"遺伝子・タンパク質",long:"T cell immunoglobulin and mucin domain containing 4（遺伝子Timd4）。アポトーシス細胞膜のホスファチジルセリンを認識する係留型efferocytosis受容体で、MASH肝マクロファージで発現が低下する。回復させると死細胞クリアランスが改善しHSC活性化・線維化が抑制されるため、機構ベースの抗線維化標的となる。"},
  "efferocytosis":{cat:"プロセス・現象",long:"マクロファージ等によるアポトーシス細胞の貪食除去過程。健常では二次壊死・炎症を防ぐが、MASHではTIM4低下により障害され、死細胞蓄積を介してHSCのプロ線維化活性化を招く。"},
  "aphc":{cat:"細胞・組織",long:"アポトーシス肝細胞（apoptotic hepatocyte）。脂肪毒性下でMASH肝に生じ、efferocytosisが追いつかないと蓄積して周囲のHSC活性化と線維化を点火する。"},
  "il-10r":{cat:"遺伝子・タンパク質",long:"インターロイキン10受容体。HSC上で活性化されるとSpp1・Timp1などプロ線維化遺伝子の発現を抑える。efferocytosisを行ったマクロファージが分泌するIL-10の作用点で、抗IL-10R抗体で抗線維化効果が消失する。"},
  "timp1":{cat:"遺伝子・タンパク質",long:"tissue inhibitor of metalloproteinases 1。マトリクスメタロプロテアーゼを阻害してECM分解を抑え線維化を促進する、活性化HSCのマーカー遺伝子。IL-10R活性化で発現が低下する。"},
  "col1a1":{cat:"遺伝子・タンパク質",long:"I型コラーゲンα1鎖。活性化HSCが過剰産生する線維化の主要細胞外基質で、Sirius red染色やαSMAと並ぶ線維化の主要読み出し指標。"},
  "clec4f":{cat:"遺伝子・タンパク質",long:"C-type lectin domain family 4 member F。Kupffer細胞に特異的に発現するマーカーで、Clec4f-CreはKC選択的に遺伝子を操作（例：Timd4欠損）するための駆動系として用いられる。"},
  "bmdm":{cat:"細胞・組織",long:"骨髄由来マクロファージ（bone marrow-derived macrophage）。レトロウイルスでTimd4を導入しTIM4+マクロファージとしてMASHマウスに移植する細胞療法のソース。"},
  "hmdm":{cat:"細胞・組織",long:"ヒト単球由来マクロファージ（human monocyte-derived macrophage）。TIMD4を導入したTIM4+ HMDMをNSGマウスに移植する、TIM4回復細胞療法のヒト版モデル。"},
  "hf-cdaa":{cat:"手法・モデル",long:"high-fat choline-deficient L-amino acid-defined diet。高脂肪・コリン欠乏アミノ酸規定食で、明確な線維化を伴うMASHを比較的短期間で再現するマウス食餌モデル。"},
  "fpc":{cat:"手法・モデル",long:"fructose-palmitate-cholesterol diet。果糖・パルミチン酸・コレステロールを組み合わせ、ヒトMASHに病態が近い線維化を生じさせるマウス食餌モデル。"},
  "tunel":{cat:"手法・モデル",long:"terminal deoxynucleotidyl transferase dUTP nick end labeling。断片化DNAを標識してアポトーシス/死細胞を検出する染色法。マクロファージマーカーとの共局在比からefferocytosis効率を定量する。"},
  "apap":{cat:"代謝・分子",long:"アセトアミノフェン（パラセタモール）。用量依存的DILIの主要原因薬。CYP2E1によりNAPQI（毒性代謝物）に変換されGSHを枯渇させ、Zone 3肝細胞に選択的な壊死をもたらす。"},
  "cfd":{cat:"手法・モデル",long:"計算流体力学（Computational Fluid Dynamics）。Navier-Stokes方程式を数値的に解き、血流速度・圧力・薬物濃度の時空間分布をシミュレートする手法。"},
  "pbpk":{cat:"手法・モデル",long:"生理的薬物動態モデル（Physiologically Based Pharmacokinetic model）。全身の臓器コンパートメントをODEで記述し、血中薬物濃度の時間推移を予測する。CFDの入口条件として使用。"},
  "dili":{cat:"疾患・病態",long:"薬物性肝障害（Drug-Induced Liver Injury）。内因性（APAP等）と特異体質性に大別され、急性肝不全の主要原因。空間的不均一性（pericentral優位）が特徴。"},
  "hlvt":{cat:"手法・モデル",long:"人体肝臓デジタルツイン（Human Liver Virtual Twin）。患者特異的な解剖画像・ゲノム・臨床データを統合し、多スケールで肝機能をシミュレートする次世代医療ツールの総称。"},
  "cco":{cat:"手法・モデル",long:"制約付き構成的最適化（Constrained Constructive Optimization）。生理的血管形成の原理（最小仕事則）に基づき、CT解像度以下のマイクロ血管ネットワークをin silicoで合成的に生成するアルゴリズム。"},
  "csm":{cat:"手法・モデル",long:"毛細血管代理モデル（Capillary Surrogate Model）。CTで解像できない直径1.5 mm以下の微細血管をCCOアルゴリズムで生成した2D合成ネットワークで代替し、~100,000小葉への境界条件を供給する。"},
  "sos":{cat:"疾患・病態",long:"類洞閉塞症候群（Sinusoidal Obstructive Syndrome）。類洞内皮・中心静脈内皮の傷害により血流が閉塞する病態で、大量化学療法や造血幹細胞移植後に典型的に現れる。本論文では血管抵抗上昇の合成シナリオとして実装された。"},
  "rock2":{cat:"シグナル・経路",long:"Rho関連キナーゼ2（ROCK2）。線維化肝の類洞内皮細胞（LSEC）と血管周囲HSCで亢進し、内皮細胞骨格を再編して血管ニッチを破綻させ、プロ線維化的なangiocrineシグナルの起点となる創薬可能な標的。"},
  "tdi01":{cat:"手法・モデル",long:"ROCK2選択的阻害薬TDI01。げっ歯類・ミニブタのMASHモデルで血管表現型を回復させ線維化を軽減し、ヒト第1相試験で良好な薬物動態・安全性と線維化低下傾向を示した。"},
  "angiocrine":{cat:"シグナル・経路",long:"内皮細胞が分泌して周囲細胞の運命を制御するパラクラインシグナル。健常LSECではNO/VEGFを介してHSCを静止させ抗線維化的に働くが、ROCK2亢進でプロ線維化シグナルへ転じる。"},
  "vegf":{cat:"シグナル・経路",long:"血管内皮増殖因子。LSECの分化・有窓構造の維持を支え、NO依存経路を介してHSC静止を保つangiocrine軸の中核。capillarizationで減弱する。"},
  "enos / no":{cat:"シグナル・経路",long:"内皮型NO合成酵素（eNOS）とその産物である一酸化窒素（NO）。LSECの抗線維化angiocrineシグナルを媒介しHSCを静止に保つが、capillarizationで産生が低下する。"},
  "caspase-8":{cat:"遺伝子・タンパク質",long:"アポトーシスを開始するシステイン-アスパラギン酸プロテアーゼ（CASP8）。本論文では細胞死とは独立した非アポトーシス機能で、肝細胞内のYY1を介して分泌Meteorinを誘導しMASH線維化を駆動する。"},
  "yy1":{cat:"遺伝子・タンパク質",long:"転写因子Yin Yang 1。肝細胞でcaspase-8の下流に働き、分泌型Meteorin（Metrn）の転写を誘導するスイッチとして機能する。"},
  "meteorin":{cat:"遺伝子・タンパク質",long:"分泌型タンパク質Meteorin（Metrn）。MASH肝細胞から分泌され、HSC上のc-Kit–STAT3経路を介してHSCを活性化する新規のHSCアクチベーター。ヒト・マウスMASH肝で増加する。"},
  "c-kit":{cat:"遺伝子・タンパク質",long:"受容体型チロシンキナーゼKIT（CD117）。肝星細胞（HSC）の膜上で肝細胞由来Meteorinを受容し、下流のSTAT3を起動してHSC活性化を伝える。"},
  "stat3":{cat:"シグナル・経路",long:"signal transducer and activator of transcription 3。c-Kitの下流でHSC活性化を媒介する転写因子/シグナル分子で、肝細胞→HSCのパラクライン線維化シグナルの実行点となる。"},
  "marco":{cat:"遺伝子・タンパク質",long:"コラーゲン様構造をもつマクロファージ受容体。常在Kupffer細胞のマーカー兼スカベンジャー受容体で、MASH進行に伴い発現が低下し常在KC枯渇の指標となる。"},
  "cd5l":{cat:"遺伝子・タンパク質",long:"CD5分子様タンパク（AIM）。常在Kupffer細胞のマーカーで、脂質代謝や細胞生存の制御に関与し、MARCOとともにKC同定に用いられる。"},
  "trem2":{cat:"遺伝子・タンパク質",long:"骨髄系細胞に発現するトリガー受容体2。脂質関連/MASH関連マクロファージ（LAM）の代表マーカーで、脂質取込や組織修復に関与する。"},
  "lpl":{cat:"代謝・分子",long:"リポタンパクリパーゼ。脂質を分解する酵素で、GPNMB+ MetMacが高発現し脂質取込・代謝適応を示すマーカーとなる。"},
  "fabp5":{cat:"遺伝子・タンパク質",long:"脂肪酸結合タンパク5。MetMacの脂質処理を担う代謝適応マーカーで、細胞内の脂肪酸輸送に関わる。"},
  "msr1":{cat:"遺伝子・タンパク質",long:"マクロファージスカベンジャー受容体1（CD204）。実質域の代謝型マクロファージで高発現し、脂質の貪食に関与する。"},
  "thp-1":{cat:"手法・モデル",long:"ヒト単球系の株化細胞。マクロファージ様に分化させ、IL32応答（貪食能やIL1B/IL10バランス）を評価するex vivo機能解析に用いる。"},
  "il1b":{cat:"シグナル・経路",long:"インターロイキン1β。炎症性サイトカインで、GPNMB+マクロファージの炎症性表現型の指標となり、IL32刺激で上昇する。"},
  "il10":{cat:"シグナル・経路",long:"インターロイキン10。抗炎症性サイトカインで、IL32刺激により低下し、IL1B優位の炎症性シフトを示す。"},
  "gpnmb":{cat:"遺伝子・タンパク質",long:"糖タンパク質NMB（オステオアクチビン）。MASH進行で増える代謝適応型/LAM系マクロファージの代表マーカーで、貪食能・抗原提示能と関連する。"},
  "il32":{cat:"シグナル・経路",long:"インターロイキン32。進行MASLDのバルーニング肝細胞が産生する炎症性サイトカインで、GPNMB+マクロファージの貪食能とIL1B優位の炎症性表現型を駆動する肝細胞→マクロファージのシグナル。"},
  "metmac":{cat:"細胞・組織",long:"代謝活性型マクロファージ（metabolically active macrophage）。GPNMB・LPL・FABP5・HS3ST2を高発現し、MASHで常在Kupffer細胞を置換して増加する亜集団。"},
  "snrna-seq":{cat:"手法・モデル",long:"単一核RNAシークエンス。細胞核から発現を測るため、凍結・固定したヒト肝組織でも単一細胞解像度のトランスクリプトームが得られる。"},
  "hla-dr":{cat:"遺伝子・タンパク質",long:"MHCクラスII分子（HLA-DR）。抗原提示能の指標で、MASHのGPNMB+マクロファージで増加し抗原提示性の獲得を示す。"},
  "spp1":{cat:"遺伝子・タンパク質",long:"分泌型リン酸化タンパク（オステオポンチン）。線維化と関連するMASHバイオマーカーで、MASHのGPNMB+マクロファージや胆管細胞で増加する。"},
  "akr1b10":{cat:"代謝・分子",long:"アルド-ケト還元酵素1B10。レチノール代謝酵素でバルーニング肝細胞のマーカー。IL32高発現域と空間的に共局在する。"},
  "pcls":{cat:"手法・モデル",long:"精密肝切片（precision-cut liver slices）。ヒト肝組織を薄切して培養するex vivoモデルで、組織構造を保ったままマクロファージ機能や脂質負荷応答を解析できる。"},
  "lam":{cat:"細胞・組織",long:"脂質関連マクロファージ。MITFを介して脂質処理能（β酸化）を高め、HGF分泌で肝保護的にも働く特殊なマクロファージ亜集団。"},
  "mitf":{cat:"遺伝子・タンパク質",long:"メラノサイトで有名な転写因子だが、LAMでは脂質処理（PGC1α–PPARγ–FAO軸）を司るマスター制御因子として機能する。"},
  "pgc1α / pparγ":{cat:"シグナル・経路",long:"ミトコンドリア生合成・脂肪酸酸化・脂質代謝・インスリン感受性を制御する転写コアクチベーター/核内受容体の軸。"},
  "fao":{cat:"代謝・分子",long:"脂肪酸β酸化。ミトコンドリアで脂肪酸をエネルギーに変える経路で、LAMの脂質処理能の中核をなす。"},
  "hgf / met":{cat:"シグナル・経路",long:"肝細胞増殖因子とその受容体チロシンキナーゼ。LAMが分泌するHGFがMETを介して肝細胞を保護・再生方向に導く。"},
  "lp-pla2 (pla2g7)":{cat:"遺伝子・タンパク質",long:"リポタンパク関連ホスホリパーゼA2。酸化リン脂質の代謝に関わる分泌酵素で、LAMに発現し炎症性脂質環境を左右する。"},
  "rspo3 / lgr6":{cat:"シグナル・経路",long:"Wntシグナルを増強するR-spondin3とその受容体LGR6。中心静脈内皮細胞–HSC間のプロ線維化クロストークを担う。"},
  "col1a1/2, loxl1, thy1":{cat:"遺伝子・タンパク質",long:"I型コラーゲン（線維化ECM主成分）、架橋酵素LOXL1、活性化HSCマーカーTHY1。いずれも線維化遺伝子プログラムの代表的リードアウト。"},
  "zonation":{cat:"プロセス・現象",long:"肝小葉が門脈〜中心静脈の酸素・栄養勾配に沿って代謝機能を分業する空間的特徴。病態も帯域依存に現れる。"},
  "visium / scrna-seq":{cat:"手法・モデル",long:"組織切片上で遺伝子発現を空間的に測る空間トランスクリプトーム（Visium）と、細胞1個ずつ発現を測るscRNA-seq。"},
  "ncf1":{cat:"遺伝子・タンパク質",long:"NADPHオキシダーゼの細胞質構成因子（p47phox）。マクロファージで活性酸素産生を介しKCの鉄恒常性とフェロトーシス感受性を制御する。"},
  "nadph oxidase":{cat:"遺伝子・タンパク質",long:"膜・細胞質サブユニットからなる活性酸素（ROS）産生酵素複合体。自然免疫の酸化的殺菌に必須でNCF1が構成因子。"},
  "kc":{cat:"細胞・組織",long:"クッパー細胞。肝類洞に常在するマクロファージで、炎症・貪食・セカンドヒット応答の主役。MASHでは脱落・置換が進む。"},
  "tlr4":{cat:"遺伝子・タンパク質",long:"Toll様受容体4。LPSや酸化リン脂質などを感知する自然免疫受容体で、肝細胞ではヘプシジン産生を誘導する。"},
  "oxpl":{cat:"代謝・分子",long:"酸化リン脂質。酸化ストレス下で生じる脂質で、TLR4を介した炎症シグナルやKCの鉄・運命制御のハブとなる。"},
  "hepcidin":{cat:"遺伝子・タンパク質",long:"肝細胞が分泌する鉄代謝制御ホルモン。鉄の細胞内貯留を促し、KCの鉄沈着→フェロトーシスを後押しする。"},
  "ferroptosis":{cat:"プロセス・現象",long:"鉄依存的な脂質過酸化により起こる制御性細胞死。MASHではKC脱落の機構として働く。"},
  "momφ":{cat:"細胞・組織",long:"単球由来マクロファージ。常在KCが減少・脱落した際に肝へ浸潤して置き換わり、炎症を増幅する。"},
  "atf4":{cat:"遺伝子・タンパク質",long:"統合的ストレス応答/ER応答の中心転写因子。線維化条件下ではストレス非依存にEMT/線維化遺伝子用の非定型エンハンサーを駆動する。"},
  "emt":{cat:"プロセス・現象",long:"上皮間葉転換。上皮細胞が間葉系様の運動性・ECM産生性を獲得する過程。線維化遺伝子プログラムと関連する。"},
  "er stress":{cat:"プロセス・現象",long:"小胞体に未成熟タンパク質が蓄積するストレス状態。UPRを誘導し、ATF4を活性化する。"},
  "upr":{cat:"プロセス・現象",long:"不全タンパク応答。ERストレスを解消するための転写・翻訳プログラムで、ATF4が本来制御する対象。"},
  "isr":{cat:"プロセス・現象",long:"統合的ストレス応答。様々なストレスがeIF2αリン酸化に収束し、ATF4をハブとして遺伝子発現を再編する仕組み。"},
  "tgfβ":{cat:"シグナル・経路",long:"TGFβ。HSC活性化・線維化を駆動する最も保存されたサイトカイン。本ライブラリではATF4を再プログラムする上流因子として登場。"},
  "αsma":{cat:"遺伝子・タンパク質",long:"α平滑筋アクチン（ACTA2）。静止期HSCが筋線維芽細胞へ活性化した指標で、線維化の代表的リードアウト。"},
  "hsc":{cat:"細胞・組織",long:"肝星細胞。類洞周囲のビタミンA貯蔵細胞で、活性化して筋線維芽細胞化しコラーゲンを産生する＝線維化の中心。"},
  "iadipo":{cat:"細胞・組織",long:"iPSC由来白色脂肪細胞。MPSで脂肪組織側を担い、GLP1R高発現でセマグルチド応答も再現する。"},
  "ihep":{cat:"細胞・組織",long:"iPSC由来肝細胞。MPSで肝側を担い、脂質蓄積・インスリン抵抗性のリードアウトを提供する。"},
  "imac":{cat:"細胞・組織",long:"iPSC由来マクロファージ。M0/M1へ分極可能で、M1化させると脂肪組織炎症（TNFα）を再現する。"},
  "mps":{cat:"手法・モデル",long:"ミクロフィジオロジカルシステム（臓器チップ）。複数の細胞/臓器槽を循環培地でつなぎ生理的相互作用を再現する培養基盤。"},
  "hir":{cat:"疾患・病態",long:"肝インスリン抵抗性。インスリンが効かず肝糖産生が抑制されない状態で、MASLD発症の代謝的指標。"},
  "wat":{cat:"細胞・組織",long:"白色脂肪組織。エネルギー貯蔵とアディポカイン分泌を担い、内臓WATの拡大・炎症がMASLDと強く相関する。"},
  "hgp":{cat:"代謝・分子",long:"肝糖産生。糖新生・グリコーゲン分解による肝からの糖放出で、HIRの機能的リードアウト。"},
  "glp1r":{cat:"遺伝子・タンパク質",long:"GLP-1受容体。セマグルチド等GLP-1作動薬の標的で、脂肪細胞に高発現し抗炎症・代謝改善に寄与する。"},
  "pdms":{cat:"手法・モデル",long:"ポリジメチルシロキサン。MPS/臓器チップの主要素材。柔軟・透明だが疎水性薬物を非特異吸着しうる点に注意が要る。"},
  "pck1":{cat:"遺伝子・タンパク質",long:"ホスホエノールピルビン酸カルボキシキナーゼ1。糖新生の律速酵素で、HIRのマーカー遺伝子。"},
  "adipoq":{cat:"遺伝子・タンパク質",long:"アディポネクチン遺伝子。脂肪細胞由来のインスリン感受性・抗炎症アディポカインで、炎症時に低下する。"},
  "tnf":{cat:"シグナル・経路",long:"腫瘍壊死因子（TNFα）。M1マクロファージが大量分泌する炎症性サイトカインで、肝のインスリン抵抗性・脂肪化を誘導する。"},
  "ppara":{cat:"遺伝子・タンパク質",long:"PPARα。肝の脂肪酸β酸化を促進する核内受容体で、セマグルチド処理で発現が増える。"},
  "capillarization":{cat:"プロセス・現象",long:"sinusoidal capillarization。LSECが特徴的な有窓と無基底膜性を失い連続基底膜をもつ毛細血管様内皮へ脱分化する病的変化で、HSC活性化・線維化を促す上流イベント。"},
  "fenestrae":{cat:"細胞・組織",long:"LSEC膜上に開く有窓(小孔)構造。血漿と肝細胞間の物質交換やHSCの静止維持に必須で、線維化で失われる。"},
  "mir-325-3p":{cat:"遺伝子・タンパク質",long:"MSCが分泌するマイクロRNA。標的Ptprmを抑制してLSECのアクチン細胞骨格を再編し、有窓を再形成してcapillarizationを逆転させる。"},
  "ptprm":{cat:"遺伝子・タンパク質",long:"受容体型タンパク質チロシンホスファターゼM。miR-325-3pの直接標的で、抑制によりアクチン細胞骨格が再編されfenestraeが再形成される。"},
  "sna":{cat:"手法・モデル",long:"球状核酸(spherical nucleic acid)。核酸を担体なしに球状へ多価提示するナノ構造で、Scara介在エンドサイトーシスを介しLSECへ核酸を送達する。"},
  "scara / sr-a":{cat:"遺伝子・タンパク質",long:"スカベンジャー受容体クラスA。線維化LSECに発現し、SNAをクラスリン依存エンドサイトーシスで選択的に取り込む受容体。"},
  "msc":{cat:"細胞・組織",long:"間葉系幹細胞。分泌するmiR-325-3pを介してLSECのcapillarizationを是正し線維化を軽減するが、移植療法には製造・安全性の制約がある。"},
  "bdl":{cat:"手法・モデル",long:"胆管結紮(bile duct ligation)。胆汁うっ滞性の肝線維化を誘導する代表的なマウスモデル。"},
  "taa":{cat:"手法・モデル",long:"チオアセトアミド。反復投与で肝傷害・線維化を誘導する実験モデル試薬。"},
  "ccl4":{cat:"手法・モデル",long:"四塩化炭素。小葉中心性の肝傷害を介して線維化を誘導する最も古典的な化学傷害モデル。"},
  "qhsc":{cat:"細胞・組織",long:"静止期肝星細胞（quiescent HSC）。ビタミンA脂質滴を貯蔵し線維化を誘発しない非活性状態。TGFβ1刺激によりaHSCへ移行する。"},
  "ahsc":{cat:"細胞・組織",long:"活性化肝星細胞（activated HSC）。TGFβ1により誘導されαSMA・I型コラーゲンを産生する筋線維芽細胞様状態。線維化ECMの主な産生源。"},
  "ihsc":{cat:"細胞・組織",long:"不活化肝星細胞（inactivated HSC）。活性化後に一時的な静止様状態に移行した中間状態。完全な静止期HSCとは異なりTGFβ1刺激で素早く再活性化でき、NASH患者の線維化ステージと相関して蓄積する。"},
  "kappa":{cat:"手法・モデル",long:"Kappaグラフ書き換え言語。分子や細胞の状態を「接触パターンの書き換えルール」として記述し、規則ベースの確率的シミュレーションを可能にする。複雑な多状態システムを少数のルールで表現できる。"},
  "ecm":{cat:"代謝・分子",long:"細胞外基質（extracellular matrix）。コラーゲン（主にI型）・フィブロネクチン・ラミニン等からなる三次元ネットワーク。線維化では活性化HSCによる過剰産生が組織硬化・肝機能障害を招く。"},
  "reversion":{cat:"プロセス・現象",long:"線維化退縮（fibrosis reversion）。TGFβ1供給が途絶えたり治療介入が入ると、iHSCの再活性化が低下しECMが徐々に分解されて線維化が退縮する現象。iHSC不活化ループの制御が治療標的として注目される。"},
  "acly":{cat:"遺伝子・タンパク質",long:"ATPクエン酸リアーゼ（ATP citrate lyase）。ミトコンドリア由来クエン酸をアセチルCoAに変換する細胞質酵素。肝細胞のDNLとコレステロール合成のアセチルCoA供給の主経路を担い、MASHの脂肪化・線維化の代謝ハブとして注目される。"},
  "acss2":{cat:"遺伝子・タンパク質",long:"アセチルCoAシンテターゼ2（acyl-CoA synthetase short chain 2）。酢酸をアセチルCoAに変換する酵素。ACLY依存経路とは独立に機能し、特に肝星細胞（HSC）においてACSS2依存の酢酸代謝がコレステロール合成・HSC活性化・線維化を駆動することが示されている。"},
  "dnl":{cat:"代謝・分子",long:"肝臓の脂質新生（de novo lipogenesis）。糖や酢酸由来のアセチルCoAを出発点として脂肪酸を新規合成する代謝経路。インスリン・糖・高栄養状態で誘導され、MASH・肥満に伴う肝TG蓄積（steatosis）の主要原因の一つ。SREBP1cやChREBPが転写制御を担う。"},
  "evt0185":{cat:"手法・モデル",long:"Espervita Therapeuticsが開発した初のACLY＋ACSS2二重阻害薬。4種のMASHマウスモデルで脂肪化・インスリン抵抗性・線維化を解消し、セマグルチドとの相乗効果を示した前臨床段階の研究ツール兼創薬候補。"},
  "srebp1c":{cat:"遺伝子・タンパク質",long:"ステロール調節エレメント結合タンパク質1c（sterol regulatory element-binding protein 1c）。インスリン・糖・エネルギー過剰に応答してFASN・ACACA等の脂肪酸合成酵素遺伝子を活性化するマスター転写因子。肝DNL誘導・steatosisの中心因子。"},
  "hmgcr":{cat:"遺伝子・タンパク質",long:"HMG-CoAレダクターゼ（3-hydroxy-3-methylglutaryl-CoA reductase）。コレステロール合成経路の律速酵素でスタチン薬の標的。HSCではACSS2由来アセチルCoAがHMGCR経路を活性化し、コレステロール合成増加→HSC活性化→線維化を促すことが示されている。"},
  "bempedoic acid":{cat:"手法・モデル",long:"高コレステロール血症に承認されたACLY単独阻害薬（ETC-1002）。スタチン不耐患者に用いられる。EVT0185との比較対照として使用され、ACLY単独より二重（ACLY＋ACSS2）阻害がMASHと線維化に対してより有効であることを示す基準となった。"},
  "meld":{cat:"疾患・病態",long:"Model for End-Stage Liver Disease。血清ビリルビン・クレアチニン・INR・ナトリウムから算出する肝疾患重症度スコア（3〜40点）。肝移植の優先順位付けや慢性肝疾患の予後予測に世界的に使用される。"},
  "amt":{cat:"手法・モデル",long:"Autologous Macrophage Therapy（自家マクロファージ療法）。患者自身の末梢血単球を採取し体外でM2様マクロファージへ分化・拡大後に静脈内輸注する細胞療法。前臨床では肝内炎症解消・線維化退縮・肝再生を促す。"},
  "m2 macrophage":{cat:"細胞・組織",long:"M2偏向マクロファージ。IL-4・IL-13・IL-10等で誘導される抗炎症・組織修復・線維化解消型の表現型。IL-10・TGFβ1分泌・コラーゲン分解促進が特徴で、MASHでのKCのM1/M2バランスが病態の悪化と退縮を決定する。"},
  "match trial":{cat:"手法・モデル",long:"Macrophage Therapy for Liver Cirrhosis trial（ISRCTN10368050）。自家単球由来マクロファージ療法の世界初の第2相オープンラベルRCT。51名の代償性肝硬変患者を対象に欧州多施設で実施。主要EP(ΔMELD@day90)は惜しくも未達だが治療群に肝関連死ゼロという安全性シグナルを示した。"},
  "wnt":{cat:"シグナル・経路",long:"Wingless-related integration site（Wnt）リガンドが起動するシグナル経路。βカテニンの安定化を通じて肝細胞のZone 3遺伝子発現・zonation・再生を制御する。HSCが産生するRSPO3によってLRP5/6受容体経由で増強される。"},
  "β-catenin (ctnnb1)":{cat:"遺伝子・タンパク質",long:"WNT/βカテニンシグナルの転写共活性化因子（CTNNB1遺伝子産物）。RSPO3→WNT活性化によって核移行し、Zone 3肝細胞遺伝子（CYP450・グリコーゲン合成等）を誘導する。zonation維持の中心分子。"},
  "cyp450":{cat:"遺伝子・タンパク質",long:"チトクロームP450酵素群（CYP1A2・CYP3A4など）。ER/ミトコンドリア局在の薬物代謝酵素。RSPO3→WNT→Zone 3のzonation維持に依存して発現し、HSC活性化（RSPO3低下）により発現低下・解毒能障害が生じる。"},
  "merfish":{cat:"手法・モデル",long:"Multiplexed Error Robust Fluorescence In Situ Hybridization（多重化エラー頑健FISH）。数百の遺伝子プローブを使い組織切片上で単一細胞・単一分子解像度の空間トランスクリプトームを取得する画像ベース手法。Visiumより解像度が高くHSCやKCなど非実質細胞を空間的に直接同定できる。"},
  "cellphonedb":{cat:"手法・モデル",long:"CellPhoneDB。細胞型間の受容体–リガンドペアを、単一細胞発現データと既知の受容体–リガンドデータベースから網羅的に推定する計算ツール。zonation依存的なHep–HSC・Hep–Mac間クロストークの推定に使用された。"},
  "cps1":{cat:"遺伝子・タンパク質",long:"カルバモイルリン酸合成酵素1（carbamoyl phosphate synthetase 1）。ミトコンドリア内でアンモニアをカルバモイルリン酸へ変換する尿素回路の第一律速酵素。線維化ヒト肝の散在性Fibrotic Hep 2集団で高発現し、傷害応答・アンモニア解毒能の指標となる。"},
  "gdf7":{cat:"シグナル・経路",long:"Growth Differentiation Factor 7。TGFβスーパーファミリーに属するリガンドで、Zone 3肝細胞が産生しHSCのBMP受容体（BMPR1A/2等）に作用する。MERFISH＋CellPhoneDBで同定されたzonation依存的な肝細胞→HSCシグナルの1つ。"},
  "thrb":{cat:"遺伝子・タンパク質",long:"甲状腺ホルモン受容体β（thyroid hormone receptor beta）。核内受容体で脂質代謝・肝代謝を制御する。線維化関連肝細胞（Fibrotic Hep 1/2）で発現上昇が確認され、THRβ選択的アゴニストであるレズメチロム（NASH治療薬として承認）の分子標的でもある。"},
  "thbs1":{cat:"遺伝子・タンパク質",long:"トロンボスポンジン1（thrombospondin 1）。HSCが産生する細胞外マトリクス関連糖タンパクで、Zone 3肝細胞が発現するCD36に作用する。MERFISH解析でHSC→Zone 3肝細胞へのシグナルペアとして同定された。"},
  "cd74":{cat:"遺伝子・タンパク質",long:"MHCクラスII不変鎖（invariant chain；別名Ii chain）。MHCクラスII分子の安定化・細胞内輸送を担うシャペロン。肝星細胞のうち門脈域に濃縮するHSC1（炎症反応性のサブセット）で高発現し、IFN-γなどの炎症シグナルで誘導される。"},
  "baysor":{cat:"手法・モデル",long:"Baysor。画像ベース空間トランスクリプトーム（MERFISH等）向けのベイズ的細胞境界推定アルゴリズム。RNA分子の近接性と事前分布から細胞境界を推定し、免疫化学染色（Cellpose）と組み合わせて使用する。"},
  "slc7a2":{cat:"遺伝子・タンパク質",long:"溶質輸送体ファミリー7メンバー2（SLC7A2；CAT-2）。アルギニン・オルニチン・リジンを輸送するカチオン性アミノ酸トランスポーターで尿素回路にオルニチン/アルギニンを供給する。線維化関連Fibrotic Hep 2で高発現し傷害肝の尿素回路適応を示す。"},
  "huvec":{cat:"細胞・組織",long:"ヒト臍帯静脈内皮細胞（human umbilical vein endothelial cell）。NHLFとともにフィブリンゲル内で自己組織化して灌流可能なマイクロ血管ネットワークを形成する。肝MPSの血管構成に標準的に使用されるが、肝特異的なLSECへの置換が今後の課題。"},
  "nhlf":{cat:"細胞・組織",long:"正常ヒト肺線維芽細胞（normal human lung fibroblast）。HUVECと協調してフィブリンゲル内の血管モルフォゲネシス（管腔形成・安定化）をサポートするストロマ細胞。MPSの血管ネットワーク形成に必須のサポート細胞として使用。"},
  "ir":{cat:"疾患・病態",long:"インスリン抵抗性（insulin resistance）。インスリンへの感受性が低下し肝糖産生が抑制されない代謝不全状態。高insulin・高glucose・高FFAを組み合わせたIR培地でin vitroモデルに誘導できる。MASLDとT2Dの両病態の根幹をなす。"},
  "g6pc":{cat:"遺伝子・タンパク質",long:"グルコース-6-ホスファターゼ触媒サブユニット（glucose-6-phosphatase catalytic subunit）。ER膜に局在し糖新生の最終反応（グルコース-6-リン酸→グルコース）を触媒する律速酵素。IR条件で上昇し、肝糖産生増大の重要な機能的指標となる。"},
  "fabp1":{cat:"遺伝子・タンパク質",long:"肝型脂肪酸結合タンパク（fatty acid binding protein 1；L-FABP）。肝細胞の細胞質に高発現し長鎖脂肪酸の細胞内輸送・代謝に関与する。IR条件でFASNとともに発現変化がみられ、脂質処理能のリードアウトとなる。"},
  "cxcl1":{cat:"シグナル・経路",long:"C-X-Cモチーフケモカインリガンド1（GROα；CXCL1）。好中球・単球の強力な走化性ケモカインで、CXCR2受容体を介して免疫細胞を病変部へ招集する。IR肝MPS上清で増加しKC活性化による炎症性サイトカイン環境の形成を示す。"},
  "cxcl2":{cat:"シグナル・経路",long:"C-X-Cモチーフケモカインリガンド2（GROβ；CXCL2）。CXCL1と同族のELRモチーフCXCケモカインで、同じCXCR2受容体を介して好中球・単球を誘引する。IR条件で協調して増加し、炎症性招集の増幅を示す。"},
  "ccl4 (mip-1β)":{cat:"シグナル・経路",long:"C-Cモチーフケモカインリガンド4（MIP-1β；CCL4）。単球・T細胞・NK細胞を走化するケモカインで、CCR1/CCR5受容体を介して作用する。IR肝MPS上清で増加し単球浸潤促進に寄与する。※化学傷害モデルで使う四塩化炭素CCl4（carbon tetrachloride）とは全く別物。"},
  "icam-1":{cat:"遺伝子・タンパク質",long:"細胞間接着分子1（intercellular adhesion molecule 1；CD54）。内皮細胞・マクロファージ表面に発現し白血球接着・血管外遊出を促進する膜タンパク。IR条件の肝MPSで分泌が上昇し内皮炎症状態と単球招集の促進を示す指標となる。"},
  "cd163":{cat:"遺伝子・タンパク質",long:"CD163（ヘモグロビンスカベンジャー受容体）。組織定着マクロファージ（M2様）の代表的表面マーカーで、ヘモグロビン・ハプトグロビン複合体の取込を介した抗炎症・組織修復機能と関連する。血管外遊出した単球でのCD163上昇が組織マクロファージへの分化開始を示す。"},
  "cd14":{cat:"遺伝子・タンパク質",long:"CD14（LPS共受容体 / 単球マーカー）。LPS結合タンパク（LBP）と協調してLPSをTLR4に提示するGPI係留型受容体。単球・マクロファージの同定・選別に使うマーカーで、CD14+で末梢血単球を精製して血管腔への添加実験に使用する。"},
  "pls-da":{cat:"手法・モデル",long:"偏最小二乗判別分析（partial least squares discriminant analysis）。多次元の測定値（サイトカイン・ケモカインパネル等）から疾患状態を判別する教師あり多変量解析手法。IR vs 生理的条件の疾患状態の有意な分離と寄与因子（CXCL1/CXCL2/CCL4/ICAM-1）の同定に使用された。"},
  "fibrin":{cat:"手法・モデル",long:"フィブリンゲル（fibrin hydrogel）。フィブリノゲンにトロンビンを加えて重合させた天然ハイドロゲル。HUVECと線維芽細胞が自己組織化してマイクロ血管ネットワークを形成するための3D足場として機能する。細胞リモデリングに適したECM代替基材。"},
  "gas6":{cat:"シグナル・経路",long:"増殖停止特異的タンパク質6（growth arrest specific protein 6；GAS6）。AXL/MER/TYRO3（TAM受容体）ファミリーのリガンドで、アポトーシス細胞の貪食誘導・抗炎症・組織修復を促進する。生理的条件の肝MPS上清で増加し組織恒常性維持の役割を担う可能性を示す。"},
  "hipsc-hsc":{cat:"細胞・組織",long:"human iPSC-derived hepatic stellate cell（人工多能性幹細胞由来胎児型肝星細胞）。WT1/DESMIN/PDGFRβを発現し胎児HSCに近い転写プロファイルを持ち、10万倍超の増殖能を維持する。Matrigel-free多細胞オルガノイドで内皮ネットワーク形成と肝成熟を促進する。"},
  "hipsc-he":{cat:"細胞・組織",long:"human iPSC-derived hepatic endoderm（iPSC由来肝内胚葉細胞）。肝細胞前駆体として機能し、HSC共存下でHNF4A発現・アルブミン分泌・CYP450活性が向上する。Matrigel-free三細胞オルガノイドの肝成熟コンポーネント。"},
  "wt1":{cat:"遺伝子・タンパク質",long:"Wilms tumor 1（ウィルムス腫瘍タンパク1）。胎児肝星細胞（fetal HSC）の転写因子マーカーで、hiPSC-HSCがWT1陽性であることが胎児型同一性の根拠となる。"},
  "hnf4a":{cat:"遺伝子・タンパク質",long:"hepatocyte nuclear factor 4 alpha（肝細胞核内受容体4α）。肝細胞成熟の主要転写因子でALB/CYP遺伝子群の発現を制御する。Matrigel-free三細胞オルガノイドでHSC共存により発現が上昇し、HSCの肝成熟促進効果の指標となる。"},
  "rora":{cat:"遺伝子・タンパク質",long:"RAR-related orphan receptor alpha（核内受容体転写因子）。HSCの糖解/OXPHOSを抑制して静止表現型を維持する。発現低下がHSC活性化の代謝スイッチを引き起こし、欠損マウスで線維化増悪、アゴニスト（SR1078等）投与で多臓器線維化が軽減する。"},
  "dihsc":{cat:"細胞・組織",long:"iPSC-differentiated hepatic stellate cell（iPSC由来肝星細胞）。Sancho-Bruら（バルセロナ）の命名で#19のhiPSC-HSCと同概念。プロテオーム軌跡解析・RORA機能解析に使用された分化誘導HSC。"},
  "oxphos":{cat:"代謝・分子",long:"oxidative phosphorylation（酸化的リン酸化）。ミトコンドリア電子伝達系によるATP産生経路。RORAが抑制することでHSCを低エネルギー・静止状態に保つ。RORA低下→OXPHOS亢進がHSC活性化の代謝的引き金となる。"},
  "sr1078":{cat:"手法・モデル",long:"SR1078（合成RORAアゴニスト）。RORα/γの選択的アゴニストでHSC活性化を抑制し線維化を軽減する薬理ツール。多臓器ペリサイト静止の検証に使用された。"},
  "lam-like kc":{cat:"細胞・組織",long:"傷害部位でTREM2↑/CD9↑のLAM表現型を採用した常在クッパー細胞（KC）。単球由来の募集LAMとは発生起源が異なるが、TREM2依存的efferocytosisによる組織修復能は機能的に等価。De Ponti et al., Immunity 2025 で同定。"},
  "proteogenomics":{cat:"手法・モデル",long:"プロテオームとトランスクリプトームを同一細胞集団で統合解析する手法。本ライブラリではLAM様KCと募集LAMの分子同一性比較（Immunity 2025）に使用。"},
  "spatial restriction":{cat:"プロセス・現象",long:"LAMとLAM様KCが傷害巣にのみ集積し健常域には少ない傷害部位特異的な分布パターン。空間トランスクリプトーム解析で可視化された。"},
  "bec":{cat:"細胞・組織",long:"biliary epithelial cell（胆管上皮細胞/胆管細胞）。胆管内腔を裏打ちする上皮細胞で、FXR–YAP軸により胆汁酸バリアを能動的に維持する。欠失でEMT→BA漏出→HSC活性化→線維化が生じる。"},
  "fxr":{cat:"遺伝子・タンパク質",long:"farnesoid X receptor（ファルネソイドX受容体）。核内受容体で胆汁酸を直接感知し、肝細胞では脂質・糖代謝を統合制御する。BECではYAPを転写活性化して胆管バリアを維持（Nat Metab 2026）。"},
  "yap":{cat:"遺伝子・タンパク質",long:"Yes-associated protein（YAP）。Hippoシグナル下流のトランスコアクチベーター。BECではFXRの転写標的として細胞接着プログラムを誘導し密着結合を維持する（Nat Metab 2026）。"},
  "oca":{cat:"手法・モデル",long:"obeticholic acid（オベチコール酸）。半合成第二世代FXRアゴニスト。MASH・PBCの臨床試験中だが、BEC特異的FXR欠失マウスで線維化を悪化させた——BECのFXR状態を考慮しない全身投与は逆効果になりうる。"},
  "plin5":{cat:"遺伝子・タンパク質",long:"perilipin 5。脂質滴（LD）表面コートタンパクのペリリピンファミリーメンバー。ミトコンドリア-LD物理的テザリングを媒介し、S155リン酸化でカップリング強度を制御（Nat Metab 2026）。"},
  "scphenomics":{cat:"手法・モデル",long:"single-cell phenomics（単一細胞フェノミクス）。高多重蛍光組織イメージング＋定量解析で単一細胞レベルの細胞内分子状態（LD・ミトコンドリア・タンパク分布）を多変量で捉える新技術（Nat Metab 2026）。"},
  "mito-ld contact":{cat:"プロセス・現象",long:"mitochondria–lipid droplet contact site（ミトコンドリア-脂質滴コンタクト部位）。脂肪酸をミトコンドリアβ酸化に直接輸送するチャンネル。絶食時↑、WD投与時↓（PLIN5 S155リン酸化依存）。"},
  "lipotoxicity":{cat:"疾患・病態",long:"細胞内LD過剰蓄積→ER stress・ミトコンドリア機能障害・アポトーシス誘導。MASLDからMASHへの進行の中心機序。mito-LDカップリング崩壊で増悪。"},
  "visium hd3":{cat:"手法・モデル",long:"10x Genomics Visium HD 第3世代。サブミクロン解像度の空間トランスクリプトームプラットフォーム。従来Visiumより高解像度で単一細胞に近い空間分解能を実現。"},
  "phenocycler":{cat:"手法・モデル",long:"AKOYA Biosciences PhenoCycler-Fusion。最大60タンパクを蛍光サイクル染色で同一組織上に同時測定する空間プロテオミクスイメージャー（#24 Nature 2026健常ヒト肝アトラスで使用）。"},
  "ep300":{cat:"遺伝子・タンパク質",long:"E1A binding protein p300。ヒストンアセチルトランスフェラーゼ型コアクチベーター。TET1（Zone1/periportal）またはHIF1α（Zone3/pericentral）と複合体を形成しゾーン特異遺伝子を活性化（#25 Takebe Nature 2025）。"},
  "tet1":{cat:"遺伝子・タンパク質",long:"ten-eleven translocation methylcytosine dioxygenase 1。DNAメチル化除去酵素。アスコルビン酸により活性化されEP300と協働してZone1（門脈周囲）プログラムを確立（#25）。"},
  "bdl":{cat:"手法・モデル",long:"bile duct ligation（胆管結紮）。外科的に総胆管を結紮し胆汁うっ滞・高ビリルビン血症・二次的線維化を誘発するラット/マウスモデル。#25でhiPSC-オルガノイド移植の有効性検証に使用。"},
  "porto-central axis":{cat:"細胞・組織",long:"門脈-中心静脈軸（porto-central axis）。肝小葉内の門脈域（Zone 1, 高O2）から中心静脈（Zone 3, 低O2）へ向かうzonation軸。酸素・栄養・BA濃度勾配の構造的基盤。ヒトではマウスより中心静脈側シフト（#24）。"},
  /* ===== KC/LSEC/HSC/マーカー群（No.27-42）の新規用語 ===== */
  "id3":{cat:"遺伝子・タンパク質",long:"inhibitor of DNA binding 3（DNA結合阻害因子3）。肝細胞が単球/KCに誘導するbHLH型転写因子で、KC identityの確立に必要なニッチシグナルの一つ。Bonnardel 2019（#27）で同定。"},
  "lxrα":{cat:"遺伝子・タンパク質",long:"liver X receptor alpha（肝X受容体α；NR1H3）。LSEC・HSCがDLL4/Notch+BMP経路を介して単球/KCに誘導する核内受容体。脂質代謝調節と並行してKC identity維持に必要。Bonnardel 2019（#27）で同定。"},
  "dll4":{cat:"遺伝子・タンパク質",long:"Delta-like ligand 4。LSEC・HSCが発現するNotchリガンドで、DLL4→Notch軸によりBMP経路と協調してKC前駆体にLXRαを誘導するKCニッチシグナルの一つ（Bonnardel 2019, #27）。"},
  "bmp9":{cat:"シグナル・経路",long:"bone morphogenetic protein 9（GDF2）。HSCが分泌するBMPファミリーリガンドで、LSEC終末分化マーカー（LYVE-1・Stab2等）を支持しfenestraeを維持する。BMP9欠損でLSECがcapillarizationに傾く（He 2024, #32）。"},
  "lyve-1":{cat:"遺伝子・タンパク質",long:"lymphatic vessel endothelial hyaluronan receptor 1（LYVE1）。LSECの終末分化マーカーで有窓LSECに高発現する。BMP9シグナル依存的に維持され、capillarizationで発現が低下するLSEC健全性の指標（He 2024, #32；Rautou 2025, #34）。"},
  "stab2":{cat:"遺伝子・タンパク質",long:"stabilin-2（FEEL-2）。LSECの終末分化マーカーで、ヒアルロン酸・修飾LDL等のスカベンジャー受容体として機能する。BMP9依存的に維持され、capillarizationで低下するLSEC identity指標（He 2024, #32）。"},
  "vsig4":{cat:"遺伝子・タンパク質",long:"V-set and immunoglobulin domain-containing protein 4（VSIG4；別名CRIg）。組織定着型マクロファージ・KC成熟の代表マーカー。PI3K/Akt→STAT3→PDK2経路を介してミトコンドリアROS産生を抑制し、LPS誘発炎症を代謝レベルでブレーキをかける（Li 2017, #40；Tasnim 2019, #31）。"},
  "cd206":{cat:"遺伝子・タンパク質",long:"CD206（マンノース受容体；MRC1）。M2様マクロファージ・GC処理KC・組織修復型マクロファージの表面マーカー。グルコルチコイド（GR活性化）によって強く誘導される（Desgeorges 2019, #41；Haematologica 2018, #42）。"},
  "endmt":{cat:"プロセス・現象",long:"endothelial-to-mesenchymal transition（内皮間葉転換）。LSEC capillarization後に部分的なEndMT状態へ移行し、α-SMAやCol1A1を直接産生する能力を獲得する現象。線維化への内皮細胞の積極的寄与を示す（Qu 2024, #35）。"},
  "lanifibranor":{cat:"手法・モデル",long:"IVA337。PPAR-α・β/δ・γの三型を同時に活性化するパン-PPARアゴニスト（phase III試験中）。LSEC capillarizationを改善し肝内血管抵抗と門脈圧を低下させた最初のヒト臨床的証拠（Rautou 2025, #34）。"},
  "pdk2":{cat:"遺伝子・タンパク質",long:"pyruvate dehydrogenase kinase 2（ピルビン酸デヒドロゲナーゼキナーゼ2）。VSIg4→PI3K/Akt→STAT3軸の下流でKCに誘導される酵素。PDHをリン酸化・不活化してピルビン酸→アセチルCoA変換（TCA供給）を抑制し、ミトコンドリア由来ROSと炎症を減弱させる（Li 2017, #40）。"},
  "rxra":{cat:"遺伝子・タンパク質",long:"retinoid X receptor alpha（レチノイドX受容体α；NR2B1）。静止期HSC（qHSC）の特徴的な転写因子で、ビタミンA貯蔵とペリサイト機能の維持に関わる。MASH進行に伴い発現が変化しquiescent状態の指標となる（Kisseleva 2025, #39）。"},
  "fosl1":{cat:"遺伝子・タンパク質",long:"FOS-like antigen 1（Fra-1）。MASH初期の「initiatory HSC」亜集団を特徴づける転写因子で、Egr3・Nfkb2とともに活性化初期の炎症性HSC状態を規定する（Kisseleva 2025, #39）。"},
  "dexamethasone":{cat:"手法・モデル",long:"デキサメタゾン（合成グルコルチコイド）。グルコルチコイド受容体（GR）を介してCD163・CD206の転写を直接誘導し、単球/マクロファージをM2様（組織修復・anti-inflammatory）表現型に誘導する。iKC分化培地の成分として、KC成熟度確認に活用（Haematologica 2018, #42；Desgeorges 2019, #41）。"},
  "ikc":{cat:"細胞・組織",long:"iPSC-derived Kupffer cell（iPSC由来クッパー細胞）。ヒトiPSCから単球様前駆体を経て、肝細胞との直接接触共培養によりVSIG4+CD163+TIMD4+LXRα+ID3+の成熟KC表現型を獲得した細胞。自分の4細胞共培養系のKCコンポーネント（Tasnim 2019, #31）。"},
  "emp":{cat:"細胞・組織",long:"erythro-myeloid progenitor（赤血球骨髄系前駆細胞）。胎生9.5日頃に卵黄嚢から発生し胎生肝に定着する、常在KCの主要胚性前駆細胞集団。生後7日に類洞内へ移行してKCとして成熟する（Nusse & Kubes 2025, #30）。"},
  "gr":{cat:"遺伝子・タンパク質",long:"glucocorticoid receptor（グルコルチコイド受容体；NR3C1）。デキサメタゾン等のGCが結合する核内受容体で、CD163プロモーターに直接結合してその転写を活性化する。GR阻害薬RU486でブロック可能（Haematologica 2018, #42）。"},
  "decm":{cat:"手法・モデル",long:"decellularized extracellular matrix（脱細胞化細胞外マトリックス）。臓器から細胞を除いて残した天然の足場で、血管・実質の空間配置を再建する土台に使う（Kim 2026, #49）。"},
  "vca":{cat:"手法・モデル",long:"vascular coating agent（血管コーティング剤）。抗CD31アプタマーを使い内皮細胞を足場の血管位置へ誘導する被覆材。血管と実質の空間的協調を助ける（Kim 2026, #49）。"},
  "igf2":{cat:"遺伝子・タンパク質",long:"insulin-like growth factor 2。IGF1R-AKT/MAPK軸を駆動して肝オルガノイドの空間構築と機能成熟を支える増殖因子。外因性添加で治療成績が向上した（Kim 2026, #49）。"},
  "igf1r":{cat:"遺伝子・タンパク質",long:"IGF1 receptor（IGF1受容体）。IGF2を受けてAKT/MAPKを活性化し、血管化肝オルガノイドの組織化の鍵となる受容体（Kim 2026, #49）。"},
  "phli-seq":{cat:"手法・モデル",long:"空間トランスクリプトームと機能摂動を結ぶ解析アプローチ。血管化肝オルガノイドの再生機序（IGF軸）の同定に用いられた（Kim 2026, #49）。"},
  "lgr5":{cat:"遺伝子・タンパク質",long:"leucine-rich repeat-containing GPCR 5。Wnt標的で幹/前駆細胞マーカー。肝前駆細胞・オルガノイドの幹性指標として使われる（Kim 2026, #49）。"},
  "hepatoblast":{cat:"細胞・組織",long:"肝芽細胞。肝細胞と胆管上皮に分化できる胎児肝の前駆細胞。iPSC由来肝オルガノイドの実質側の出発細胞（Kim 2026, #49）。"},
  "lsec":{cat:"細胞・組織",long:"liver sinusoidal endothelial cell（肝類洞内皮細胞）。有窓構造でNOを出しHSCを静止に保つが、毛細血管化すると線維化を促す。c-Kit勾配でPC〜PPに階層化される（#50, #53, #54）。"},
  "fbxw7":{cat:"遺伝子・タンパク質",long:"F-box and WD repeat domain-containing 7。NOTCH1等を分解するE3ユビキチンリガーゼで、LSECでは線維化のブレーキ。欠損でN1ICDが安定化する（Yan 2026, #50）。"},
  "notch1":{cat:"シグナル・経路",long:"notch receptor 1。切断で生じたN1ICDが核でRBPJと転写を駆動する。LSECで過剰だと毛細血管化・線維化を促す（Yan 2026, #50）。"},
  "n1icd":{cat:"遺伝子・タンパク質",long:"NOTCH1 intracellular domain（NOTCH1細胞内ドメイン）。NOTCH1の活性型で、FBXW7が分解する標的。安定化するとSEMA3G転写が高まる（Yan 2026, #50）。"},
  "sema3g":{cat:"遺伝子・タンパク質",long:"semaphorin 3G。FBXW7欠損LSECで最も上がる分泌因子で、HSCのNRP2を介して線維化を促すパラクリン因子（Yan 2026, #50）。"},
  "rbpj":{cat:"遺伝子・タンパク質",long:"recombination signal binding protein for Ig kappa J region。N1ICDと複合体を作りNotch標的（SEMA3G等）を転写する中核因子（Yan 2026, #50）。"},
  "nrp2":{cat:"遺伝子・タンパク質",long:"neuropilin 2。HSC側のSEMA3G受容体で、LSEC由来の線維化シグナルの受け手（Yan 2026, #50）。"},
  "samac":{cat:"細胞・組織",long:"scar-associated macrophage（瘢痕関連マクロファージ；TREM2+）。慢性肝疾患で線維化ニッチに集まる疾患拡大マクロファージ。OLR1+の炎症性亜集団を含む（Ramachandran 2026, #51）。"},
  "olr1":{cat:"遺伝子・タンパク質",long:"oxidized LDL receptor 1（LOX-1）。炎症性SAMacが発現するスカベンジャー受容体。高発現が線維化・予後不良と相関し、治療標的候補（Ramachandran 2026, #51）。"},
  "cld":{cat:"疾患・病態",long:"chronic liver disease（慢性肝疾患）。各種病因で線維化が進み予後を悪化させる病態の総称。単一細胞アトラスの対象（Ramachandran 2026, #51）。"},
  "single-cell atlas":{cat:"手法・モデル",long:"多数の検体から単一細胞レベルで細胞状態を網羅した参照地図。本研究では健常・CLD由来64.9万細胞で125状態を解像（Ramachandran 2026, #51）。"},
  "kat5":{cat:"遺伝子・タンパク質",long:"lysine acetyltransferase 5（TIP60）。ACSS2と複合体を作り、ヒストンのクロトニル化を介してAIF1転写を上げ炎症を駆動する（Wen 2026, #52）。"},
  "aif1":{cat:"遺伝子・タンパク質",long:"allograft inflammatory factor 1。ACSS2-KAT5がヒストンクロトニル化で誘導する標的で、肝炎症と肝細胞老化を促しMASH化を進める（Wen 2026, #52）。"},
  "histone crotonylation":{cat:"プロセス・現象",long:"ヒストンのリジンがクロトニル基で修飾されるエピジェネティック修飾。ACSS2-KAT5がこれを介して炎症遺伝子（AIF1）を活性化する（Wen 2026, #52）。"},
  "navitoclax":{cat:"手法・モデル",long:"BCL-2/BCL-xL阻害薬（ABT-263）。老化細胞を除くセノリティクスとして、老化肝細胞が関わるMASH進行の治療候補に挙げられる（Wen 2026, #52）。"},
  "hffd":{cat:"手法・モデル",long:"high-fat high-fructose diet（高脂肪高フルクトース食）。MASLD/MASHを誘導するマウス食餌モデル（Wen 2026, #52）。"},
  "rxrg":{cat:"遺伝子・タンパク質",long:"retinoid X receptor gamma（レチノイドX受容体γ）。PC LSECでFGF1の転写を駆動する核内受容体。レチノイン酸がリガンド（Fang 2026, #53）。"},
  "ra":{cat:"代謝・分子",long:"retinoic acid（レチノイン酸）。ビタミンAの活性代謝物でRXRのリガンド。LSEC由来FGF1軸を強め脂肪化を抑える（Fang 2026, #53）。"},
  "fgf1":{cat:"遺伝子・タンパク質",long:"fibroblast growth factor 1。PC LSECがRXRG依存で分泌し、肝細胞のFGFR4を介して脂質蓄積を抑える抗脂肪化因子（Fang 2026, #53）。"},
  "fgfr4":{cat:"遺伝子・タンパク質",long:"fibroblast growth factor receptor 4。肝細胞側のFGF1受容体で、脂質蓄積の抑制シグナルを受ける（Fang 2026, #53）。"},
  "bodipy":{cat:"手法・モデル",long:"boron-dipyrromethene。中性脂質を染める蛍光色素で、脂肪滴の空間分布を可視化する（Fang 2026, #53）。"},
  "shear stress":{cat:"プロセス・現象",long:"haemodynamic shear stress（ずり応力）。血流が血管壁に与える力。LSECがこれをセンスしてアンギオクリンWntを調節する（Lee 2026, #54）。"},
  "wnt2":{cat:"遺伝子・タンパク質",long:"Wnt family member 2。PC LSECが出すアンギオクリンWntリガンドで、肝細胞のβ-catenin標的/GSを支える（Lee 2026, #54）。"},
  "wnt9b":{cat:"遺伝子・タンパク質",long:"Wnt family member 9b。PC LSEC由来のWntリガンド。Wnt2と並び肝zonationを維持する（Lee 2026, #54）。"},
  "fzd4":{cat:"遺伝子・タンパク質",long:"frizzled class receptor 4。Wnt受容体で、PC LSECに濃集し血管側で自律的（オートクリン）にWntを受ける（Lee 2026, #54）。"},
  "lrp6":{cat:"遺伝子・タンパク質",long:"LDL receptor related protein 6。Wntの共受容体で、FZDと組んでβ-cateninシグナルを起動する（Lee 2026, #54）。"},
  "double-iecko":{cat:"手法・モデル",long:"内皮Wnt（リガンド/受容体）を二重に欠損させる誘導型内皮特異的ノックアウト。肝のzonationが崩れる（Lee 2026, #54）。"},
  "cx37":{cat:"遺伝子・タンパク質",long:"connexin 37（GJA4）。血管Wntがオートクリンに制御するギャップ結合分子で、LSEC間の連絡を担う（Lee 2026, #54）。"},
  "cx43":{cat:"遺伝子・タンパク質",long:"connexin 43（GJA1）。ギャップ結合分子で、血管Wntに調節され細胞間の電気・代謝的連絡に関わる（Lee 2026, #54）。"},
  "gs":{cat:"遺伝子・タンパク質",long:"glutamine synthetase（Glul）。PC肝細胞のzonationマーカーで、アンギオクリンWntに依存して発現する（Lee 2026, #54）。"},
  "liv2trans":{cat:"手法・モデル",long:"Latent In Vitro to In Vivo Translation。MPSとin vivoの分子データを潜在空間で写像し、翻訳性を上げる実験条件を提案する機械学習枠組み（Cadavid 2026, #55）。"},
  "translatability":{cat:"プロセス・現象",long:"in vitroの結果がヒト（in vivo）をどれだけ予測できるかの度合い。LIV2TRANSが定量化の対象とする（Cadavid 2026, #55）。"},
  "latent variable model":{cat:"手法・モデル",long:"高次元の分子データを低次元の潜在空間に圧縮し、異なる系（MPSとin vivo）を突き合わせる統計/機械学習手法（Cadavid 2026, #55）。"},
  "jak":{cat:"シグナル・経路",long:"Janus kinase（ヤヌスキナーゼ）。サイトカイン受容体に結合してSTATをリン酸化するキナーゼ。IFNシグナルの中核で、摂動がMPS翻訳性を上げうる（Cadavid 2026, #55）。"},
  "stat":{cat:"遺伝子・タンパク質",long:"signal transducer and activator of transcription。JAKで活性化し核へ移る転写因子。JAK-STAT摂動が予測性能を上げうる（Cadavid 2026, #55）。"},
  "interferon":{cat:"代謝・分子",long:"interferon（IFN）。JAK-STATを介する炎症/抗ウイルスサイトカイン。MPSの翻訳性を上げる追加摂動として提案された（Cadavid 2026, #55）。"},
  "easyscp":{cat:"手法・モデル",long:"Easy single-cell proteomics。FACS分取＋384ウェル1ステップ消化＋高感度MSを統合した高スループット単一細胞プロテオミクス法（Hao 2026, #56）。"},
  "scp":{cat:"手法・モデル",long:"single-cell proteomics（単一細胞プロテオミクス）。単一細胞のタンパク質を網羅測定する手法。従来は工程が複雑で普及が限られていた（Hao 2026, #56）。"},
  "hss":{cat:"手法・モデル",long:"hepatocyte spatial status score。215の保存zonationマーカーから算出し、肝細胞のゾーン座標を推定・再構成するスコア（Hao 2026, #56）。"},
  "dia":{cat:"手法・モデル",long:"data-independent acquisition。全イオンを網羅的に断片化して定量する質量分析モードで、微量試料でも再現性が高い（Hao 2026, #56）。"},
  "facs":{cat:"手法・モデル",long:"fluorescence-activated cell sorting。蛍光で細胞を1個ずつ分取する手法で、単一細胞解析の入力を作る（Hao 2026, #56）。"},
  "zonation marker":{cat:"手法・モデル",long:"ゾーン依存性が保存された基準タンパク質/遺伝子。HSSなどゾーン座標推定の土台になる（Hao 2026, #56）。"},
  "senolytics":{cat:"手法・モデル",long:"老化細胞を選択的に死滅させる薬剤。D+Q等があり、線維化・炎症の軽減を狙う（Koning 2026, #57）。"},
  "d+q":{cat:"手法・モデル",long:"dasatinib plus quercetin。ダサチニブ（キナーゼ阻害）＋ケルセチン（フラボノイド）の併用セノリティクス。間欠投与する（Koning 2026, #57）。"},
  "senescence":{cat:"プロセス・現象",long:"cellular senescence（細胞老化）。分裂を止めたままSASPを出し続ける細胞状態で、肝の炎症・線維化を駆動する（Koning 2026, #57; Wen 2026, #52）。"},
  "mash":{cat:"疾患・病態",long:"metabolic dysfunction-associated steatohepatitis。脂肪化に炎症・肝細胞障害・線維化が重なった病態で、線維化進行で予後が悪化する（#52, #57, #58）。"},
  "nas":{cat:"手法・モデル",long:"NAFLD activity score。脂肪化・小葉炎症・肝細胞風船様変性の合計スコアで、MASHの活動性指標（Koning 2026, #57）。"},
  "fibrosis stage":{cat:"疾患・病態",long:"肝線維化の進行度（F0〜F4）。1段階以上の改善がセノリティクス試験の主要評価項目（Koning 2026, #57）。"},
  "trnp1":{cat:"遺伝子・タンパク質",long:"TMF1-regulated nuclear protein 1。脾CD8 T細胞でエピ再編により立ち上がる転写因子で、FURIN/CTSDを誘導しINSR-α分泌を促す（Zhang 2026, #58）。"},
  "insr-α":{cat:"遺伝子・タンパク質",long:"insulin receptor alpha subunit（インスリン受容体α鎖）。TRNP1+ CD8 T細胞が分泌する線維化促進因子で、HSCを活性化する。中和が治療標的（Zhang 2026, #58）。"},
  "furin":{cat:"遺伝子・タンパク質",long:"furin（プロタンパク質転換酵素）。TRNP1に誘導され、INSR-αの成熟・切り出しを担う（Zhang 2026, #58）。"},
  "ctsd":{cat:"遺伝子・タンパク質",long:"cathepsin D（カテプシンD）。プロテアーゼで、TRNP1に誘導されINSR-αのエクトドメイン・シェディングに関わる（Zhang 2026, #58）。"},
  "cd8 t cell":{cat:"細胞・組織",long:"CD8+ T細胞（細胞傷害性T細胞）。脾臓で再プログラムされ、線維化促進性のTRNP1+サブセットになる（Zhang 2026, #58）。"},
  "h3k27ac":{cat:"プロセス・現象",long:"histone H3 lysine 27 acetylation。活性型エンハンサー/プロモーターの印で、増加がTRNP1発現の立ち上げに寄与する（Zhang 2026, #58）。"},
  "h3k27me3":{cat:"プロセス・現象",long:"histone H3 lysine 27 trimethylation。抑制性のヒストン修飾で、再分布がクロマチン再編とTRNP1発現に関与する（Zhang 2026, #58）。"},
  "tad":{cat:"プロセス・現象",long:"topologically associating domain。クロマチンが会合する空間ドメインで、再編によりエンハンサー-プロモーター接触が変わる（Zhang 2026, #58）。"},
  "ersodetug":{cat:"手法・モデル",long:"INSR-αを中和する抗体。in vivo投与でMASLD/MASH誘発の肝線維化を軽減した（Zhang 2026, #58）。"},
};
