/* ============================================================
   js/catinfo.js — 用語ビュー用のカテゴリとやや詳しい解説
   キーは用語（glossary の term）の小文字。新しい用語はここに1行追加する。
   未登録の用語は「その他」として表示される（scripts/check.mjs が警告を出す）。
   ============================================================ */

/* ===== 用語カテゴリ＆やや詳しい解説（用語ビュー用。tooltipは各論文glossaryの簡潔descを使用） ===== */
const CAT_ORDER=["細胞・組織","遺伝子・タンパク質","シグナル・経路","代謝・分子","プロセス・現象","手法・モデル","疾患・病態"];
const CATINFO={
  "leads":{cat:"手法・モデル",long:"hiPSC由来の肝細胞・HSC・LSEC・KCを側流路つきマイクロ流体チップに配置したMASHモデル。FFA・フルクトースにLPSとPAAを第2ヒットとして加えるとMASH様の表現型が得られるが、薬剤を投与しても線維化の可逆性は限定的だった（Balachander 2025, #48）。"},
  "resmetirom":{cat:"代謝・分子",long:"肝選択的な甲状腺ホルモン受容体βアゴニストで、MASHの承認薬。LEADSでは薬剤応答の評価に用いられた（#48）。"},
  "vehicle":{cat:"手法・モデル",long:"薬剤や脂質を溶かす溶媒だけを与える対照。溶媒自体の効果を切り分けるために置くもので、欠くと溶媒の寄与を評価できない。LEADSではresmetiromの健常群にvehicle対照が置かれていない点が限界として挙げられている（#48）。"},
  "smfish":{cat:"手法・モデル",long:"single-molecule fluorescence in situ hybridization。個々のmRNA分子を組織切片上で数える手法で、位置情報を保ったまま定量できる。"},
  "periportal":{cat:"細胞・組織",long:"門脈周囲（zone 1）。酸素が高く、糖新生やアンモニア処理が優位な領域。"},
  "pericentral":{cat:"細胞・組織",long:"中心静脈周囲（zone 3）。酸素が低く解糖や薬物代謝が優位な領域で、Wntの供給源でもある。早期MASLDの脂肪化が始まる領域として#53で示された。"},
  "landmark gene":{cat:"手法・モデル",long:"ゾーン依存性が既知で、単一細胞の小葉座標を推定する基準として使われる遺伝子。"},
  "lobule":{cat:"細胞・組織",long:"肝小葉。肝の構造単位で、六角形の頂点に門脈域、中心に中心静脈を持つ。"},
  "taz":{cat:"遺伝子・タンパク質",long:"transcriptional coactivator with PDZ-binding motif。Hippo経路のエフェクターで、NASH肝細胞で上昇しTEADと組んでIhhを誘導し線維化を駆動する。"},
  "wwtr1":{cat:"遺伝子・タンパク質",long:"WW domain containing transcription regulator 1。TAZをコードする遺伝子名で、発現量を測る際はこちらの名称を用いる。"},
  "tead":{cat:"遺伝子・タンパク質",long:"TEA domain transcription factor。TAZやYAPと複合体を形成してDNAに結合し、標的遺伝子の転写を起動する。"},
  "ihh":{cat:"遺伝子・タンパク質",long:"Indian hedgehog。TAZ/TEADが誘導する分泌因子で、肝細胞から肝星細胞へ線維化シグナルを渡すパラクリンの担い手。"},
  "paa":{cat:"代謝・分子",long:"phenylacetic acid（フェニル酢酸）。芳香族アミノ酸の微生物代謝産物で、慢性投与により脂肪化とBCAA代謝の変化を誘導する。日本では覚醒剤原料に該当し取扱いに指定が要る。"},
  "bcaa":{cat:"代謝・分子",long:"branched-chain amino acid（分岐鎖アミノ酸）。ロイシン・イソロイシン・バリンを指し、脂肪化に伴って代謝が脱制御される。"},
  "metagenomics":{cat:"手法・モデル",long:"便などの試料に含まれる全微生物ゲノムを網羅的に配列決定し、菌叢の構成と機能ポテンシャルを推定する手法。"},
  "gene richness":{cat:"プロセス・現象",long:"腸内細菌叢が持つ遺伝子の多様度。脂肪化を有する患者で低く、その低下は代謝性疾患と結びつく。"},
  "fmt":{cat:"手法・モデル",long:"fecal microbiota transplantation（糞便微生物叢移植）。菌叢の因果的寄与を検証するための介入手段。"},
  "proteobacteria":{cat:"細胞・組織",long:"LPSを産生するグラム陰性菌を多く含む細菌門。脂肪化群で優位となり、エンドトキシン生合成の遺伝的ポテンシャルの高さと結びつく。"},
  "high-resolution respirometry":{cat:"手法・モデル",long:"酸素電極を用いて単離ミトコンドリアの酸素消費を高感度に測定する手法。#44では肝生検から単離したミトコンドリアの呼吸を直接定量するのに用いられた。"},
  "maximal respiration":{cat:"プロセス・現象",long:"基質と脱共役剤を飽和させたときに到達する最大の酸素消費速度。ミトコンドリア量と切り離して「質」を評価でき、NASHでは量が多いのに最大呼吸が低下していた。"},
  "uncoupling":{cat:"プロセス・現象",long:"電子伝達とATP合成の共役が外れ、熱として散逸する状態。NASH肝では脱共役とリークが増えており、最大呼吸の低下と並行していた。"},
  "8-ohdg":{cat:"代謝・分子",long:"8-hydroxy-2'-deoxyguanosine。酸化的DNA損傷の代表的マーカーで、NASH肝では酸化ストレスの亢進や抗酸化能の低下と並行して増加していた。"},
  "nafl":{cat:"疾患・病態",long:"non-alcoholic fatty liver。炎症や線維化を伴わない単純性脂肪肝の段階。#44では、肥満者の最大呼吸は脂肪肝の有無を問わず高く、NASHの段階で低下した。"},
  "hepatic mitochondrial flexibility":{cat:"プロセス・現象",long:"肥満に伴うインスリン抵抗性の初期に、肝が呼吸能を押し上げる適応。NASHの段階で失われる（#44）。"},
  "ffa":{cat:"代謝・分子",long:"free fatty acid（遊離脂肪酸）。培地に加えて肝細胞に脂肪滴を蓄積させる基本入力で、飽和/不飽和の比によって毒性が大きく変わる。"},
  "oa":{cat:"代謝・分子",long:"oleic acid（オレイン酸、C18:1）。一価不飽和脂肪酸で脂肪滴に取り込まれやすく毒性が低い。OA:PA=2:1の混合は、ヒト脂肪肝と同程度の脂質蓄積を与えつつ毒性とアポトーシスを軽微にとどめた（#43）。"},
  "pa":{cat:"代謝・分子",long:"palmitic acid（パルミチン酸、C16:0）。飽和脂肪酸で小胞体ストレスとアポトーシスを誘導しやすい。PAのみ（0:3）では同程度の蓄積に急性の細胞傷害が伴った（#43）。"},
  "benign chronic steatosis":{cat:"疾患・病態",long:"傷害を伴わない慢性的な脂肪蓄積の段階。OA:PA=2:1条件が模す病態で、脂肪蓄積と細胞傷害を切り分けて調べる土台になる（#43）。"},
  "ntf3":{cat:"遺伝子・タンパク質",long:"neurotrophin-3。神経栄養因子ファミリーの分泌リガンド。進行期NASHで活性化HSCが分泌し、自己の受容体NTRK3(TrkC)に自己分泌的に結合してHSC活性化を維持する。"},
  "ntrk3":{cat:"遺伝子・タンパク質",long:"neurotrophic receptor tyrosine kinase 3。TrkCをコードする受容体型チロシンキナーゼで、NTF3の受容体。進行期HSCの自己分泌回路の標的で、薬理学的阻害により進行期マウスNASH線維化が退縮した。"},
  "trkc":{cat:"遺伝子・タンパク質",long:"tropomyosin receptor kinase C（NTRK3がコード）。HSC膜上でNTF3を受け取り活性化シグナルを伝える受容体タンパク。NTRK2(TrkB)と同じTrk受容体ファミリー。"},
  "autocrine":{cat:"プロセス・現象",long:"自己分泌。細胞が分泌した因子が同じ細胞自身の受容体に作用するシグナル様式。進行期HSCではNTF3→NTRK3の自己分泌ループが活性化を自己維持し線維化を駆動する。"},
  "nash":{cat:"疾患・病態",long:"non-alcoholic steatohepatitis（非アルコール性脂肪肝炎、現在はMASHに改称）。脂肪化に炎症・肝細胞傷害・線維化を伴う段階。"},
  "3d mlho":{cat:"手法・モデル",long:"three-dimensional multi-lineage hepatic organoid。hESC由来の5細胞種（肝細胞・胆管細胞・HSC・内皮・Kupffer細胞）を肝に近い比率（HEP 60％・他4種を各10％）で集合させた三次元肝オルガノイド。肝細胞単独培養よりヒト肝組織に近い遺伝子発現・高いCYP活性・免疫応答能を示し、間接的肝毒性の評価に用いられた。"},
  "hesc":{cat:"細胞・組織",long:"human embryonic stem cell（ヒト胚性幹細胞）。段階的分化により肝の5細胞種を作り出す出発材料。"},
  "heps":{cat:"細胞・組織",long:"hepatocytes（肝細胞）。ALB/CYP3A4を発現する肝実質細胞で3D MLHOの約60％を占める主要細胞。"},
  "cho":{cat:"細胞・組織",long:"cholangiocytes（胆管細胞）。CK19/SOX9/HNF6陽性で胆管様管腔を形成する非実質細胞。"},
  "imp":{cat:"手法・モデル",long:"imipramine（イミプラミン）。三環系抗うつ薬。肝細胞単独では無毒だが3D MLHOでのみ強い毒性を示し、本論文の間接的肝毒性の主役となった薬剤。"},
  "trkb":{cat:"遺伝子・タンパク質",long:"tropomyosin receptor kinase B（NTRK2がコード）。神経栄養因子受容体チロシンキナーゼで、HSCに高発現し、IMPの既報の結合標的として間接的肝毒性の起点となる。"},
  "ntrk2":{cat:"遺伝子・タンパク質",long:"neurotrophic receptor tyrosine kinase 2。TrkBをコードする遺伝子で、scRNA-seqでHSCに最も高発現する。"},
  "p53":{cat:"遺伝子・タンパク質",long:"tumor protein p53（TP53）。ストレス応答・腫瘍抑制の転写因子で、IMP–TrkB下流のHSCで上昇しmiR-34a-3p産生を促す。"},
  "hnrnpa2b1":{cat:"遺伝子・タンパク質",long:"heterogeneous nuclear ribonucleoprotein A2/B1。miRNAをエクソソームへ選別的に積み込むRNA結合タンパクで、IMPで上昇する。"},
  "dgcr8":{cat:"遺伝子・タンパク質",long:"DiGeorge syndrome critical region 8。miRNAプロセシング（Microprocessor複合体）構成因子で、IMPで上昇しmiR-34a-3p産生を支える。"},
  "mir-34a-3p":{cat:"遺伝子・タンパク質",long:"microRNA-34a-3p。p53応答性miRNAで、毒性エクソソームに選択的に濃縮され肝細胞でXIAPを抑制してアポトーシスを誘導する細胞間伝令分子。"},
  "xiap":{cat:"遺伝子・タンパク質",long:"X-linked inhibitor of apoptosis protein。抗アポトーシスタンパクでmiR-34a-3pの直接標的。抑制されるとcaspase3が活性化し肝細胞がアポトーシスする。"},
  "caspase3":{cat:"シグナル・経路",long:"cysteine-aspartic protease 3。アポトーシス実行カスパーゼで、XIAP低下により活性化して肝細胞死を実行する（cleaved caspase3で検出）。"},
  "exosome":{cat:"代謝・分子",long:"径100〜150 nmの細胞外小胞（toxic-EXOs）。miRNA等を運ぶ細胞間伝令で、IMP下では積荷がmiR-34a-3pに偏って『毒性エクソソーム』化する（総量・サイズは不変）。"},
  "gw4869":{cat:"手法・モデル",long:"中性スフィンゴミエリナーゼ阻害薬。エクソソーム生合成を遮断し、IMPの間接的肝毒性を軽減した。"},
  "antagomir-34":{cat:"手法・モデル",long:"miR-34を中和する化学修飾アンチセンス（antagomir）。in vivoでIMP肝障害を軽減し、miR-34a-3p依存性を裏づけた。"},
  "nta":{cat:"手法・モデル",long:"nanoparticle tracking analysis（ナノ粒子トラッキング解析）。エクソソームの濃度・粒径分布を計測する手法。"},
  "scrank":{cat:"手法・モデル",long:"単一細胞解像度で薬剤–標的摂動をシミュレートし、最も応答する細胞集団を順位づけるin silico手法。本論文でHSCを最応答性の細胞と予測した。"},
  "celltiter-glo":{cat:"手法・モデル",long:"ATP量から細胞生存率を定量する発光アッセイ。58薬剤スクリーニングの毒性判定に用いた。"},
  "cmax":{cat:"代謝・分子",long:"maximum plasma concentration（最高血漿中濃度）。薬剤を臨床曝露に近い用量で試験するための基準濃度。"},
  "osm":{cat:"シグナル・経路",long:"Oncostatin M。肝細胞成熟を促すサイトカインで、HGF・デキサメタゾンと併用してHEP分化に用いた。"},
  "cyp3a4":{cat:"遺伝子・タンパク質",long:"cytochrome P450 3A4。主要な薬物代謝酵素で、3D MLHOで2D比約6倍の活性を示し肝機能成熟の指標となった。"},
  "ngfr":{cat:"遺伝子・タンパク質",long:"nerve growth factor receptor（p75）。HSC特異的表面マーカーで分化HSCの同定に用いた。"},
  "pdgfr-β":{cat:"遺伝子・タンパク質",long:"platelet-derived growth factor receptor beta。HSC/ペリサイトのマーカー受容体で分化HSCの同定に用いた。"},
  "desmin":{cat:"遺伝子・タンパク質",long:"desmin（デスミン）。中間径フィラメントでHSCの細胞骨格マーカー。分化HSCの同定に用いた。"},
  "cd9":{cat:"遺伝子・タンパク質",long:"cluster of differentiation 9（テトラスパニン）。#18ではエクソソーム表面マーカーで、抗体で取り込みを阻害でき、毒性エクソソームの肝細胞取り込みを担う。#22ではTREM2・GPNMBとともにLAM表現型の定義に使われる。"},
  "tsg101":{cat:"遺伝子・タンパク質",long:"tumor susceptibility gene 101。多胞体由来エクソソームのマーカータンパクで、単離エクソソームの同定に用いた。"},
  "shgs":{cat:"手法・モデル",long:"老化肝細胞遺伝子シグネチャ（senescent hepatocyte gene signature）。in vitro/in vivoの肝細胞老化モデルから定義された遺伝子セットで、複数マウスモデルと大規模ヒトコホートでMASLDの進行・退縮に一致して変動する、老化肝細胞バーデンの読み出し指標。"},
  "senolytic":{cat:"手法・モデル",long:"老化細胞を選択的に除去する薬剤の総称（セノリティック）。#17では肝細胞老化に効くDpCを化合物スクリーニングで同定した。"},
  "dpc":{cat:"手法・モデル",long:"di-2-pyridylketone 4-cyclohexyl-4-methyl-3-thiosemicarbazone。約2,100化合物のスクリーニングで見出されたDp44mTの類縁体（経口活性に優れる）で、銅依存的に作用し、増殖中の肝細胞への毒性が小さく老化肝細胞に選択的に効くセノリティック。CDA-HFD誘導MASHの雄マウスで老化・脂肪化・炎症・線維化・細胞死のマーカーを低減した。"},
  "gdf15":{cat:"遺伝子・タンパク質",long:"growth differentiation factor 15。老化肝細胞が分泌するSASP因子で、血中濃度がSHGS量・疾患進行と並行して上昇するバイオマーカー。snRNA-seqの細胞間相互作用解析ではTGFBR2を介して肝の各細胞種に作用しうると推定されたが、GDF15–TGFBR2軸自体の機能実証はない。"},
  "tgfbr2":{cat:"遺伝子・タンパク質",long:"TGF-β受容体2型（TGF-β receptor type 2）。細胞間相互作用解析でGDF15の受け手側受容体として推定された（機能実証はなし）。"},
  "p21":{cat:"遺伝子・タンパク質",long:"サイクリン依存性キナーゼ阻害因子1A（CDKN1A）。細胞周期停止を担い、SHGS+老化肝細胞はp21+細胞に由来する。"},
  "sasp":{cat:"プロセス・現象",long:"老化関連分泌表現型（senescence-associated secretory phenotype）。老化細胞が放出する炎症・線維化促進性の分泌因子群で、GDF15などを含み周囲組織の病態を駆動する。"},
  "sa-β-gal":{cat:"手法・モデル",long:"老化関連β-ガラクトシダーゼ（senescence-associated β-galactosidase）。細胞老化の代表的染色マーカーで、パルボシクリブ誘導の老化肝細胞でほぼ100%陽性となる。"},
  "palbociclib":{cat:"手法・モデル",long:"CDK4/6阻害薬（PD-0332991）。肝細胞に強固で不可逆的な細胞周期停止＝老化を誘導し、本論文ではSHGS構築の老化モデルに用いられた。"},
  "cdk4/6":{cat:"シグナル・経路",long:"サイクリン依存性キナーゼ4/6。細胞周期のG1/S移行を駆動し、阻害すると細胞周期が停止して細胞老化が誘導される。"},
  "cellular senescence":{cat:"プロセス・現象",long:"ストレス等で誘導される不可逆的な細胞周期停止状態。SASPを伴って周囲組織に影響し、MASLDでは老化肝細胞の蓄積が病態進行と関連する。"},
  "huh7":{cat:"細胞・組織",long:"ヒト肝がん由来株化細胞（Huh7）。パルボシクリブ処理で強固な老化表現型を示し、SHGS構築の老化モデルに使用された。"},
  "tim4":{cat:"遺伝子・タンパク質",long:"T cell immunoglobulin and mucin domain containing 4（遺伝子Timd4）。アポトーシス細胞膜のホスファチジルセリンを認識する係留型efferocytosis受容体で、MASH肝マクロファージで発現が低下する。回復させると死細胞クリアランスが改善しHSC活性化・線維化が抑制されるため、機構ベースの抗線維化標的となる。"},
  "efferocytosis":{cat:"プロセス・現象",long:"マクロファージ等によるアポトーシス細胞の貪食除去過程。健常では二次壊死・炎症を防ぐが、MASHではTIM4低下により障害され、死細胞蓄積を介してHSCのプロ線維化活性化を招く（#16）。#22では、死細胞の取込そのものがマクロファージのLAM表現型への誘導シグナルにもなることが示された。"},
  "aphc":{cat:"細胞・組織",long:"アポトーシス肝細胞（apoptotic hepatocyte）。脂肪毒性下でMASH肝に生じ、efferocytosisが追いつかないと蓄積して周囲のHSC活性化と線維化を点火する。"},
  "il-10r":{cat:"遺伝子・タンパク質",long:"インターロイキン10受容体。HSC上で活性化されるとSpp1・Timp1などプロ線維化遺伝子の発現を抑える。efferocytosisを行ったマクロファージが分泌するIL-10の作用点で、抗IL-10R抗体で抗線維化効果が消失する。"},
  "timp1":{cat:"遺伝子・タンパク質",long:"tissue inhibitor of metalloproteinases 1。マトリクスメタロプロテアーゼを阻害してECM分解を抑え線維化を促進する、活性化HSCのマーカー遺伝子。IL-10R活性化で発現が低下する。"},
  "col1a1":{cat:"遺伝子・タンパク質",long:"I型コラーゲンα1鎖。活性化HSCが過剰産生する線維化の主要細胞外基質で、Sirius red染色やαSMAと並ぶ線維化の主要読み出し指標。"},
  "clec4f":{cat:"遺伝子・タンパク質",long:"C-type lectin domain family 4 member F。Kupffer細胞に特異的に発現するマーカーで、Clec4f-CreはKC選択的に遺伝子を操作（例：Timd4欠損）するための駆動系として用いられる。"},
  "bmdm":{cat:"細胞・組織",long:"骨髄由来マクロファージ（bone marrow-derived macrophage）。#16では移植後の肝局在確認などに用いられ、移植するTIM4+細胞（マウス）はTimd4を導入した造血幹細胞から分化させたマクロファージ。"},
  "hmdm":{cat:"細胞・組織",long:"ヒト単球由来マクロファージ（human monocyte-derived macrophage）。TIMD4を導入したTIM4+ HMDMをNSGマウスに移植する、TIM4回復細胞療法のヒト版モデル。"},
  "hf-cdaa":{cat:"手法・モデル",long:"high-fat choline-deficient L-amino acid-defined diet。高脂肪・コリン欠乏アミノ酸規定食で、明確な線維化を伴うMASHを比較的短期間で再現するマウス食餌モデル。"},
  "fpc":{cat:"手法・モデル",long:"fructose-palmitate-cholesterol diet。果糖・パルミチン酸・コレステロールを組み合わせ、ヒトMASHに病態が近い線維化を生じさせるマウス食餌モデル。"},
  "tunel":{cat:"手法・モデル",long:"terminal deoxynucleotidyl transferase dUTP nick end labeling。断片化DNAを標識してアポトーシス/死細胞を検出する染色法。マクロファージマーカーとの共局在比からefferocytosis効率を定量する。"},
  "apap":{cat:"代謝・分子",long:"アセトアミノフェン（パラセタモール）。DILIの主原因薬で、#15ではCFD多スケールモデルの検証テストケースとして用いられ、Zone 3（pericentral）選択的な肝細胞壊死が再現された。"},
  "cfd":{cat:"手法・モデル",long:"計算流体力学（Computational Fluid Dynamics）。Navier-Stokes方程式を数値的に解き、血流速度・圧力・薬物濃度の時空間分布をシミュレートする手法。"},
  "pbpk":{cat:"手法・モデル",long:"生理的薬物動態モデル（Physiologically Based Pharmacokinetic model）。全身の臓器コンパートメントをODEで記述し、血中薬物濃度の時間推移を予測する。CFDの入口条件として使用。"},
  "dili":{cat:"疾患・病態",long:"薬物性肝障害（Drug-Induced Liver Injury）。#15では内因性（APAP等）と特異体質性に分かれ急性肝不全の主要原因とされ、#18では直接型・特異体質型・間接型に大別して間接型の機序が解かれた。"},
  "hlvt":{cat:"手法・モデル",long:"人体肝臓デジタルツイン（Human Liver Virtual Twin）。患者特異的な多スケール計算モデルの総称で、#15はその開発の重要な一歩と位置づけられる。"},
  "cco":{cat:"手法・モデル",long:"制約付き構成的最適化（Constrained Constructive Optimization）。生理的血管形成の原理に基づき、合成血管ネットワークをin silicoで生成するアルゴリズム。"},
  "csm":{cat:"手法・モデル",long:"毛細血管代理モデル（Capillary Surrogate Model）。CT解像度以下の血管（50 µm〜1.5 mm）をCCOで生成した合成ネットワークで代替し、約100,000小葉の入口速度・薬物濃度を算出する。計算の都合で2D平面を採用している（#15）。"},
  "sos":{cat:"疾患・病態",long:"類洞閉塞症候群（Sinusoidal Obstructive Syndrome）。類洞内皮・中心静脈内皮の傷害による血流閉塞病態。#15では、一部の小葉の出口圧を上げる合成シナリオ（実臨床例ではない）として再現された。"},
  "rock2":{cat:"シグナル・経路",long:"Rho関連キナーゼ2（ROCK2）。線維化肝の類洞内皮細胞（LSEC）と血管周囲HSCで亢進し、内皮細胞骨格を再編して血管ニッチを破綻させ、プロ線維化的なangiocrineシグナルの起点となる。選択的阻害薬TDI01の標的。"},
  "tdi01":{cat:"手法・モデル",long:"ROCK2選択的阻害薬TDI01。げっ歯類・ミニブタのMASHモデルで血管表現型を回復させ線維化を軽減し、ヒト第1相試験で良好な薬物動態・安全性を示した。拡大試験では6例中5例で線維化の低下傾向が観察されたが、少数例の傾向レベルにとどまる。"},
  "angiocrine":{cat:"シグナル・経路",long:"内皮細胞が分泌して周囲細胞の運命を制御するパラクラインシグナル。健常LSECではNO/VEGFを介してHSCを静止させ抗線維化的に働くが、ROCK2亢進でプロ線維化シグナルへ転じる（#14）。肝ではWntが代表的なangiocrine因子（#54）。"},
  "vegf":{cat:"シグナル・経路",long:"血管内皮増殖因子。#14ではLSECの分化・有窓構造の維持を支え、NO依存経路を介してHSC静止を保つangiocrine軸の中核とされる。#19ではHSC由来の血管新生因子として、内皮細胞の遊走・増殖を促し血管ネットワーク形成を誘導する。"},
  "enos / no":{cat:"シグナル・経路",long:"内皮型NO合成酵素（eNOS）とその産物である一酸化窒素（NO）。LSECの抗線維化angiocrineシグナルを媒介しHSCを静止に保つが、capillarizationで減弱する。"},
  "caspase-8":{cat:"遺伝子・タンパク質",long:"アポトーシスを開始するシステイン-アスパラギン酸プロテアーゼ（CASP8）。本論文では細胞死とは独立した非アポトーシス機能で、肝細胞内のYY1を介して分泌Meteorinを誘導しMASH線維化を駆動する。"},
  "yy1":{cat:"遺伝子・タンパク質",long:"転写因子Yin Yang 1。肝細胞でcaspase-8の下流に働き、分泌型Meteorin（Metrn）の転写を誘導する。"},
  "meteorin":{cat:"遺伝子・タンパク質",long:"分泌型タンパク質Meteorin（Metrn）。MASH肝細胞から分泌され、HSC上のc-Kit–STAT3経路を介してHSCを活性化する新規のHSCアクチベーター。ヒト・マウスMASH肝で増加する。"},
  "c-kit":{cat:"遺伝子・タンパク質",long:"受容体型チロシンキナーゼKIT（CD117）。#13では肝星細胞（HSC）の膜上で肝細胞由来Meteorinを受容し、下流のSTAT3を起動してHSC活性化を伝える。#53では著者らがLSEC zonationの鍵と位置づける分子で、PC LSECに濃く発現する。"},
  "stat3":{cat:"シグナル・経路",long:"signal transducer and activator of transcription 3。c-Kitの下流でHSC活性化を媒介する転写因子/シグナル分子で、肝細胞→HSCのパラクライン線維化シグナルの実行点となる。"},
  "marco":{cat:"遺伝子・タンパク質",long:"コラーゲン様構造をもつマクロファージ受容体。常在Kupffer細胞のマーカー兼スカベンジャー受容体で、MASH進行に伴い発現が低下し常在KC枯渇の指標となる。"},
  "cd5l":{cat:"遺伝子・タンパク質",long:"CD5分子様タンパク（AIM）。常在Kupffer細胞のマーカーで、脂質代謝や細胞生存の制御に関与し、MARCOとともにKC同定に用いられる。"},
  "trem2":{cat:"遺伝子・タンパク質",long:"骨髄系細胞に発現するトリガー受容体2。脂質関連/MASH関連マクロファージ（LAM）の代表マーカーで、脂質取込や組織修復に関与する。#22ではLAMとLAM様KCのどちらか一方のTREM2が保たれれば修復が成立し、#51では瘢痕関連マクロファージ（SAMac）のマーカーとされる。"},
  "lpl":{cat:"代謝・分子",long:"リポタンパクリパーゼ。脂質を分解する酵素で、GPNMB+ MetMacが高発現し脂質取込・代謝適応を示すマーカーとなる。"},
  "fabp5":{cat:"遺伝子・タンパク質",long:"脂肪酸結合タンパク5。MetMacの脂質処理を担う代謝適応マーカーで、細胞内の脂肪酸輸送に関わる。"},
  "msr1":{cat:"遺伝子・タンパク質",long:"マクロファージスカベンジャー受容体1（CD204）。実質域の代謝型マクロファージで高発現し、脂質の貪食に関与する。"},
  "thp-1":{cat:"手法・モデル",long:"ヒト単球系の株化細胞。マクロファージ様に分化させ、IL32応答（脂質貪食・IL1B/IL10）の検証に用いた。単球様の細胞株で、初代KC/単球由来マクロファージの完全な代替ではない（#10）。"},
  "il1b":{cat:"シグナル・経路",long:"インターロイキン1β。炎症性サイトカインで、GPNMB+マクロファージの炎症性表現型の指標。THP-1ではPA存在下でIL32により上昇した。"},
  "il10":{cat:"シグナル・経路",long:"インターロイキン10。抗炎症性サイトカイン。#10のTHP-1ではIL32刺激（PA存在下）で低下してIL1B優位の炎症性シフトを示し、#16ではefferocytosisを行ったマクロファージが分泌してHSCのプロ線維化活性化を抑える。"},
  "gpnmb":{cat:"遺伝子・タンパク質",long:"糖タンパク質NMB（オステオアクチビン）。MASH進行で増える代謝適応型マクロファージ（MetMac）の代表マーカーで、貪食・抗原提示能と関連する。LAMシグネチャを示すのは一部のみで、従来のLAM/SAMとは区別される（#10）。#22ではTREM2・CD9とともにLAM表現型の定義マーカーとして用いられる。"},
  "il32":{cat:"シグナル・経路",long:"インターロイキン32。バルーニング肝細胞（AKR1B10+）の多い領域で発現が高いサイトカイン。THP-1では脂質貪食とMSR1/GPNMB小胞形成を高め、PA存在下でIL1B応答を増強しIL10を低下させた。効果はTHP-1での検証にとどまり、受容体・下流経路は未特定。"},
  "metmac":{cat:"細胞・組織",long:"代謝活性型マクロファージ（metabolically active macrophage）。GPNMB・LPL・FABP5・HS3ST2を高発現する亜集団で、常在Kupffer細胞の減少と並行してMASHで増加する（骨髄系細胞中のGPNMB+割合は非MASH 5.7%→MASH 12%）。従来のLAM/SAMとは区別される。"},
  "snrna-seq":{cat:"手法・モデル",long:"単一核RNAシークエンス。細胞核から発現を測るため、凍結・固定したヒト肝組織でも単一細胞解像度のトランスクリプトームが得られる。"},
  "hla-dr":{cat:"遺伝子・タンパク質",long:"MHCクラスII分子（HLA-DR）。抗原提示能の指標で、GPNMB+/HLA-DR+マクロファージがMASHで増加することがタンパクレベルで確認された。"},
  "spp1":{cat:"遺伝子・タンパク質",long:"分泌型リン酸化タンパク（オステオポンチン）。線維化と関連するLAM/SAM系マーカー。#10ではGPNMB+SPP1+細胞は少数で、SPP1+マクロファージの割合はMASL→MASHで変化しなかった。#16では活性化HSCのプロ線維化遺伝子で、IL-10R活性化により発現が抑制される。"},
  "akr1b10":{cat:"代謝・分子",long:"アルド-ケト還元酵素1B10。レチノール代謝酵素でバルーニング肝細胞のマーカー。IL32高発現域と空間的に共局在する。"},
  "pcls":{cat:"手法・モデル",long:"精密肝切片（precision-cut liver slices）。ヒト肝組織を薄切して培養するex vivoモデル。#10ではGPNMB+マクロファージの機能解析に用いられ、脂質負荷でGPNMB+細胞の凝集・肥大が観察された。"},
  "lam":{cat:"細胞・組織",long:"脂質関連マクロファージ。#01ではMITFを介して脂質処理能（β酸化）を高め、HGF分泌で肝保護的に働くことが示された（細胞株での検証）。#22ではTREM2/CD9/GPNMB陽性のマクロファージで、単球由来の募集LAMとLAM様KCに区別され、#28ではMASLDで増加する亜集団として整理される。"},
  "mitf":{cat:"遺伝子・タンパク質",long:"LAM特異的なマスター転写因子。PGC1α–PPARγ–FAO軸を介してミトコンドリア機能と脂質処理能を高める（OE/KD・OCRで検証、#01）。"},
  "pgc1α / pparγ":{cat:"シグナル・経路",long:"ミトコンドリア生合成・脂肪酸酸化・脂質代謝を転写レベルで制御する転写コアクチベーター/核内受容体の軸。"},
  "fao":{cat:"代謝・分子",long:"脂肪酸β酸化。ミトコンドリアで脂肪酸をエネルギーに変える経路で、LAMの脂質処理能の中核をなす。"},
  "hgf / met":{cat:"シグナル・経路",long:"肝細胞増殖因子とその受容体チロシンキナーゼ。LAMが分泌するHGFがMETを介して肝保護的に働く軸（細胞株で検証）。"},
  "lp-pla2 (pla2g7)":{cat:"遺伝子・タンパク質",long:"リポタンパク関連ホスホリパーゼA2。LAMのリン脂質代謝酵素で酸化リン脂質代謝に関与し、MASLD特異的リン脂質蓄積との関連が示唆された。"},
  "rspo3 / lgr6":{cat:"シグナル・経路",long:"Wntシグナルを増強するR-spondin3とその受容体LGR6。進行MASH（F3–4）の線維化巣で、中心静脈内皮細胞とHSCのプロ線維化クロストークを担う候補経路として計算予測された（CellPhoneDB・空間解析のみで、実験的検証は未実施）。"},
  "col1a1/2, loxl1, thy1":{cat:"遺伝子・タンパク質",long:"I型コラーゲン（線維化ECM主成分）、架橋酵素LOXL1、活性化HSCマーカーTHY1。いずれも線維化遺伝子プログラムの代表的リードアウト。"},
  "zonation":{cat:"プロセス・現象",long:"肝小葉が門脈〜中心静脈の酸素・栄養勾配に沿って代謝機能を分業する空間的特徴。病態も帯域依存に現れる。"},
  "visium / scrna-seq":{cat:"手法・モデル",long:"組織切片上で遺伝子発現を空間的に測る空間トランスクリプトーム（Visium）と、細胞1個ずつ発現を測るscRNA-seq。"},
  "ncf1":{cat:"遺伝子・タンパク質",long:"NADPHオキシダーゼの細胞質構成因子。マクロファージNCF1が酸化リン脂質を増やし、肝細胞TLR4–ヘプシジン経路を介してKCの鉄沈着とフェロトーシスを促す（#02）。"},
  "nadph oxidase":{cat:"遺伝子・タンパク質",long:"活性酸素（ROS）産生酵素複合体で、全身の自然免疫に必須。NCF1が構成因子。"},
  "kc":{cat:"細胞・組織",long:"クッパー細胞。肝類洞に常在するマクロファージで、炎症・貪食・セカンドヒット応答の主役。MASHでは脱落・置換が進む。"},
  "tlr4":{cat:"遺伝子・タンパク質",long:"Toll様受容体4。自然免疫受容体で、#02では酸化リン脂質を感知して肝細胞のヘプシジン産生を促す。#38ではLPSで活性化されるTLR4–NF-κB軸としてHSC-マクロファージの炎症–線維化連関に寄与する。"},
  "oxpl":{cat:"代謝・分子",long:"酸化リン脂質。マクロファージNCF1によって増え、TLR4を介して肝細胞のヘプシジン産生を誘導し、KC運命のハブとなる。"},
  "hepcidin":{cat:"遺伝子・タンパク質",long:"肝細胞が産生する鉄代謝制御ホルモン（HAMP）。#02ではKCへの鉄沈着を促し、続くフェロトーシスを後押しする。"},
  "ferroptosis":{cat:"プロセス・現象",long:"鉄依存的な脂質過酸化により起こる制御性細胞死。MASHではKC脱落の機構として働く。"},
  "momφ":{cat:"細胞・組織",long:"monocyte-derived macrophage（単球由来マクロファージ）。病態で肝に流入する単球由来マクロファージの総称で、moKCやLAMを含む。#02ではマクロファージNCF1がMoMΦ浸潤を促し、#51ではSAMacの供給源になりうる。役割はサブセットごとに検討途上（#28）。"},
  "atf4":{cat:"遺伝子・タンパク質",long:"統合的ストレス応答/ER応答の中心転写因子。線維化条件下ではストレス非依存にEMT/線維化遺伝子用の非定型エンハンサーを駆動する。"},
  "emt":{cat:"プロセス・現象",long:"上皮間葉転換。上皮細胞が間葉系様の運動性・ECM産生性を獲得する過程。#03では線維化遺伝子プログラムと関連し、#23ではBEC-FXR/YAP欠失で誘導されて密着結合の消失と胆汁酸漏出を引き起こす。"},
  "er stress":{cat:"プロセス・現象",long:"小胞体に未成熟タンパク質が蓄積するストレス状態。UPRを誘導し、ATF4を活性化する。"},
  "upr":{cat:"プロセス・現象",long:"不全タンパク応答。ERストレスを解消するための転写・翻訳プログラムで、ATF4が本来制御する対象。"},
  "isr":{cat:"プロセス・現象",long:"統合的ストレス応答。様々なストレスがeIF2αリン酸化に収束し、ATF4をハブとして遺伝子発現を再編する仕組み。"},
  "tgfβ":{cat:"シグナル・経路",long:"TGFβ。HSC活性化・線維化を駆動する保存されたサイトカイン。#03ではATF4を再プログラムする上流因子として登場し、#55ではMPSの翻訳性にとって決定的な手がかりとされた。"},
  "αsma":{cat:"遺伝子・タンパク質",long:"α平滑筋アクチン（ACTA2）。静止期HSCが筋線維芽細胞へ活性化した指標で、線維化の代表的リードアウト。"},
  "hsc":{cat:"細胞・組織",long:"肝星細胞。類洞周囲のビタミンA貯蔵細胞で、活性化して筋線維芽細胞化しコラーゲンを産生する＝線維化の中心。"},
  "iadipo":{cat:"細胞・組織",long:"iPSC由来白色脂肪細胞。MPSで脂肪組織側を担い、GLP1R高発現でセマグルチド応答も再現する。"},
  "ihep":{cat:"細胞・組織",long:"iPSC由来肝細胞。MPSで肝側を担い、脂質蓄積・インスリン抵抗性のリードアウトを提供する。"},
  "imac":{cat:"細胞・組織",long:"iPSC由来マクロファージ。M0/M1へ分極可能で、M1型iMACは脂肪組織炎症を惹起し、TNFαなど炎症性サイトカインの上昇を伴う（#04）。"},
  "mps":{cat:"手法・モデル",long:"ミクロフィジオロジカルシステム（臓器チップ）。複数の細胞/臓器槽を循環培地でつなぎ生理的相互作用を再現する培養基盤。#55ではin vivoへの翻訳性が課題とされる。"},
  "hir":{cat:"疾患・病態",long:"肝インスリン抵抗性。インスリンが効かず肝糖産生が抑制されない状態で、MASLD発症の代謝的指標。"},
  "wat":{cat:"細胞・組織",long:"白色脂肪組織。エネルギー貯蔵とアディポカイン分泌を担う。#04ではWAT量の増大だけでは生理的範囲でHIRは誘導されず、炎症が決定的なドライバーだった。"},
  "hgp":{cat:"代謝・分子",long:"肝糖産生。糖新生・グリコーゲン分解による肝からの糖放出で、HIRの機能的リードアウト。"},
  "glp1r":{cat:"遺伝子・タンパク質",long:"GLP-1受容体。セマグルチドの標的で、#04ではiADIPOに高発現し、その作動を介して抗炎症・肝保護効果が生じた。"},
  "pdms":{cat:"手法・モデル",long:"ポリジメチルシロキサン。MPS/臓器チップの主要素材。柔軟・透明だが疎水性薬物を非特異吸着しうる点に注意が要る。"},
  "pck1":{cat:"遺伝子・タンパク質",long:"ホスホエノールピルビン酸カルボキシキナーゼ1。糖新生の律速酵素で、HIRのマーカー遺伝子。"},
  "adipoq":{cat:"遺伝子・タンパク質",long:"アディポネクチン遺伝子。脂肪細胞由来のインスリン感受性アディポカイン。"},
  "tnf":{cat:"シグナル・経路",long:"腫瘍壊死因子（TNFα）。M1型iMACが大量分泌する炎症性サイトカイン。#04ではiHEPの脂質蓄積・HIRに伴って上昇したが、TNFα自体の因果は未検証。"},
  "ppara":{cat:"遺伝子・タンパク質",long:"PPARα。肝の脂肪酸β酸化を促進する核内受容体。"},
  "capillarization":{cat:"プロセス・現象",long:"sinusoidal capillarization。LSECが有窓(fenestrae)を失い、基底膜を形成して毛細血管様内皮へ脱分化する病的変化で、HSC活性化・線維化を促す上流イベント。#34ではヒトMASLDで単純性脂肪化の小葉域からCD34染色で増加し、線維化と相関した。#33では免疫抑制から炎症促進への転換を伴う。"},
  "fenestrae":{cat:"細胞・組織",long:"LSEC膜上に開く有窓(小孔)構造。血漿と肝細胞間の物質交換やHSCの静止維持に必須で、線維化で失われる。"},
  "mir-325-3p":{cat:"遺伝子・タンパク質",long:"MSCが分泌するマイクロRNA。標的Ptprmを抑制してLSECの細胞骨格（アクチン・微小管）を再編し、有窓を再形成してcapillarizationを逆転させる。"},
  "ptprm":{cat:"遺伝子・タンパク質",long:"受容体型タンパク質チロシンホスファターゼM。miR-325-3pの直接標的で、抑制によりアクチン・微小管の細胞骨格が再編され、fenestraeが再形成される。"},
  "sna":{cat:"手法・モデル",long:"球状核酸(spherical nucleic acid)。核酸を担体なしに球状へ多価提示するナノ粒子で、Scara/SR-A介在のクラスリン依存エンドサイトーシスにより線維化LSECへ選択的に送達される。#50ではSEMA3G siRNAの送達に用いられた。"},
  "scara / sr-a":{cat:"遺伝子・タンパク質",long:"スカベンジャー受容体クラスA。線維化LSECに発現し、SNAをクラスリン依存エンドサイトーシスで選択的に取り込む受容体。"},
  "msc":{cat:"細胞・組織",long:"間葉系幹細胞。分泌するmiR-325-3pを介してLSECのcapillarizationを是正し線維化を軽減するが、臨床応用には製造や安全性の制約が多い。"},
  "bdl":{cat:"手法・モデル",long:"胆管結紮(bile duct ligation)。外科的に総胆管を結紮し、胆汁うっ滞・高ビリルビン血症・二次的線維化を誘発するラット・マウスモデル。#05では線維化モデルの一つとして、#25ではhiPSC由来オルガノイド移植の効果検証に用いられた。"},
  "taa":{cat:"手法・モデル",long:"チオアセトアミド。反復投与で肝傷害・線維化を誘導する実験モデル試薬。"},
  "ccl4":{cat:"手法・モデル",long:"四塩化炭素。代表的な化学傷害性の肝線維化モデルで、#05ではCCl4・TAA・BDLの3モデルの一つとして用いられた。"},
  "qhsc":{cat:"細胞・組織",long:"静止期肝星細胞（quiescent HSC）。ビタミンA脂質滴を貯蔵し線維化を誘発しない非活性状態。TGFβ1刺激によりaHSCへ移行する。"},
  "ahsc":{cat:"細胞・組織",long:"活性化肝星細胞（activated HSC）。TGFβ1により誘導されαSMA・I型コラーゲンを産生する筋線維芽細胞様状態。線維化ECMの主な産生源。"},
  "ihsc":{cat:"細胞・組織",long:"不活化肝星細胞（inactivated HSC、#06）。活性化後に一時的な静止様状態へ移行した中間状態で、TGFβ1刺激で再活性化しうる。高線維化群（F3–F4）のNASH患者RNA-seqでiHSC遺伝子セットが濃縮し、線維化進行の新規マーカー候補とされた（因果は未実証）。なお#48ではiPSC由来HSC（iHSC）を指し、分化終盤のレチノール＋パルミチン酸で活性化しやすい。"},
  "kappa":{cat:"手法・モデル",long:"Kappaグラフ書き換え言語。分子や細胞の状態を「接触パターンの書き換えルール」として記述し、規則ベースの確率的シミュレーションを可能にする。"},
  "ecm":{cat:"代謝・分子",long:"細胞外基質（extracellular matrix）。コラーゲン・フィブロネクチン等の線維化基質で、線維化では過剰沈着して臓器硬化を招く（#06）。#35ではEndMTを起こしたLSECも産生に寄与しうるとされる。"},
  "reversion":{cat:"プロセス・現象",long:"線維化退縮（fibrosis reversion）。TGFβ1供給が停止するとiHSCの再活性化が低下し、ECMが分解されて線維化が退縮する現象。シミュレーションでは退縮期にMFBの不活化が進み、iHSCが再活性化しうる集団として蓄積したが、治療標的としての検証は未実施。"},
  "acly":{cat:"遺伝子・タンパク質",long:"ATPクエン酸リアーゼ（ATP citrate lyase）。クエン酸をアセチルCoAに変換する酵素で、DNLとコレステロール合成の主要なアセチルCoA供給源。#52ではACSS2と機能的に独立とされる。"},
  "acss2":{cat:"遺伝子・タンパク質",long:"アセチルCoAシンテターゼ2（acyl-CoA synthetase short chain 2）。酢酸をアセチルCoAに変換する酵素。#07ではHSCにおけるACSS2依存の酢酸代謝とコレステロール合成がHSC活性化の主要ドライバーとされ、#52では核移行してKAT5と組み、ヒストンのクロトニル化を介してAIF1を上げ、ACLYとは機能的に独立にMASHを悪化させる。"},
  "dnl":{cat:"代謝・分子",long:"肝臓の脂質新生（de novo lipogenesis）。アセチルCoAから脂肪酸を新規合成する経路で、肝steatosisの主因。"},
  "evt0185":{cat:"手法・モデル",long:"Espervita Therapeuticsが開発したACLYとACSS2の二重阻害薬。4種の独立したMASHマウスモデルで血清・肝TG、インスリン抵抗性、線維化を軽減し、ACLY単独阻害より有効だった。HSCを直接標的として活性化を抑える前臨床段階の薬剤。"},
  "srebp1c":{cat:"遺伝子・タンパク質",long:"ステロール調節エレメント結合タンパク質1c（sterol regulatory element-binding protein 1c）。インスリン・糖に応答して脂肪酸合成遺伝子を活性化するマスター転写因子で、肝DNL・steatosisの中心因子。"},
  "hmgcr":{cat:"遺伝子・タンパク質",long:"HMG-CoAレダクターゼ（3-hydroxy-3-methylglutaryl-CoA reductase）。コレステロール合成経路の律速酵素でスタチン薬の標的。#07ではHSCにおけるACSS2依存の酢酸代謝とコレステロール合成の低下が線維化解消の主要ドライバーとされた。"},
  "bempedoic acid":{cat:"手法・モデル",long:"高コレステロール血症に承認されたACLY単独阻害薬（ETC-1002）。#07ではEVT0185の比較対照として用いられ、ACLY単独阻害よりEVT0185の二重阻害の方が有効だった。"},
  "meld":{cat:"疾患・病態",long:"Model for End-Stage Liver Disease。肝疾患重症度スコア（3〜40点）で、肝移植の優先度・予後予測に使用される。#08ではMELD 10〜17の代償性肝硬変が対象で、主要評価項目は90日MELD変化量だった。"},
  "amt":{cat:"手法・モデル",long:"Autologous Macrophage Therapy（自家マクロファージ療法）。患者自身の単球を体外でマクロファージへ分化・拡大して輸注する細胞療法。輸注細胞は体外で成熟させた単球由来マクロファージで、CD163・CD206・CD169を高発現する。第2相RCT（MATCH01）では主要評価項目は未達だったが、治療群で肝関連の重篤有害事象・死亡はゼロだった。"},
  "m2 macrophage":{cat:"細胞・組織",long:"M2偏向マクロファージ。抗炎症・組織修復に働くとされるマクロファージ表現型。#08の輸注細胞は体外で成熟させた単球由来マクロファージで、CD163・CD206・CD169高発現（修復・炎症消退関連マーカー）を示すが、論文がM2と断定しているわけではない。線維化バイオマーカーに群間差はなかった。"},
  "match trial":{cat:"手法・モデル",long:"Macrophage Therapy for Liver Cirrhosis（MATCH01）。代償性肝硬変（MELD 10〜17）を対象に、自家単球由来マクロファージ療法（n=27）と標準治療（n=24）を比較した英国3施設の第2相オープンラベルRCT（計51名）。主要評価項目の90日MELD変化量の群間差は−0.87（P=0.06）で統計的有意に届かなかったが、360日の追跡で治療群に肝関連の重篤有害事象・死亡はゼロだった。"},
  "wnt":{cat:"シグナル・経路",long:"Wingless-related integration site（Wnt）リガンドが起動するシグナル経路。発生・幹細胞・肝代謝を制御する分泌型リガンドファミリーで、WNT/βカテニンシグナルを介して肝細胞のzonationや再生に関わる。HSCに豊富なRSPO3がLGR4/5受容体を介してWntシグナルを増強する（#09）。"},
  "β-catenin (ctnnb1)":{cat:"遺伝子・タンパク質",long:"WNTシグナルの転写共活性化因子（CTNNB1遺伝子産物）。RSPO3→WNT活性化で核移行し、Zone 3肝細胞遺伝子を誘導する（#09）。"},
  "cyp450":{cat:"遺伝子・タンパク質",long:"チトクロームP450酵素群（CYP1A2・CYP3A4など）。ER/ミトコンドリア局在の薬物代謝酵素。RSPO3→WNT→Zone 3のzonation維持に依存して発現し、HSC枯渇やHSC選択的Rspo3欠損でCYP450依存の解毒能が変化する（#09）。"},
  "merfish":{cat:"手法・モデル",long:"Multiplexed Error Robust Fluorescence In Situ Hybridization（多重化エラー頑健FISH）。数百遺伝子を単一細胞解像度で空間定量する画像ベース手法。#11では317遺伝子を健常3例・線維化3例の肝に適用したが、遺伝子パネルが限られ、非実質細胞の解像度はsnRNA-seqより低い。#24ではzonal markerの空間局在の解析に用いられた。"},
  "cellphonedb":{cat:"手法・モデル",long:"CellPhoneDB。細胞型間の受容体–リガンドペアを、発現データから網羅的に推定する計算ツール。#11ではzonation依存的な細胞間相互作用の推定に用いられたが、計算予測が中心で生体内の因果は未確立。"},
  "cps1":{cat:"遺伝子・タンパク質",long:"カルバモイルリン酸合成酵素1（carbamoyl phosphate synthetase 1）。尿素回路の律速酵素。線維化ヒト肝の散在性Fibrotic Hep 2で高発現する。"},
  "gdf7":{cat:"シグナル・経路",long:"Growth Differentiation Factor 7。TGFβスーパーファミリーのリガンドで、Zone 3肝細胞からHSCのBMP受容体へ分泌される。MERFISH＋snRNA-seq統合で同定されたzonation依存的な受容体–リガンドペアの一つ（計算予測が中心）。"},
  "thrb":{cat:"遺伝子・タンパク質",long:"甲状腺ホルモン受容体β（thyroid hormone receptor beta）。核内受容体で、線維化関連肝細胞（Fibrotic Hep 1/2）で発現上昇が確認され、THRβ選択的アゴニストであるレズメチロムの分子標的でもある。"},
  "thbs1":{cat:"遺伝子・タンパク質",long:"トロンボスポンジン1（thrombospondin 1）。HSCが産生しZone 3肝細胞のCD36に作用するマトリクス糖タンパク。MERFISH＋snRNA-seq統合で解析されたzonation依存的な受容体–リガンドの候補（計算予測が中心）。"},
  "cd74":{cat:"遺伝子・タンパク質",long:"MHCクラスII不変鎖（invariant chain；別名Ii chain）。MHCクラスII分子の安定化因子。肝星細胞のうち門脈域に濃縮するHSC1で高発現し、抗原提示能または活性化履歴の違いを反映する可能性がある。"},
  "baysor":{cat:"手法・モデル",long:"Baysor。画像ベース空間トランスクリプトーム（MERFISH等）向けの、RNA分布を考慮した細胞境界推定ツール。#11ではCellposeと組み合わせて細胞セグメンテーションに用いられ、測定結果はその精度に依存する。"},
  "slc7a2":{cat:"遺伝子・タンパク質",long:"溶質輸送体ファミリー7メンバー2（SLC7A2）。カチオン性アミノ酸トランスポーター（オルニチン/アルギニン）で、線維化関連のFibrotic Hep 2で高発現する。"},
  "huvec":{cat:"細胞・組織",long:"ヒト臍帯静脈内皮細胞（human umbilical vein endothelial cell）。NHLFとともにフィブリンゲル内で自己組織化して灌流可能なマイクロ血管ネットワークを形成する。#12の系は肝特異的なLSECを含まない。"},
  "nhlf":{cat:"細胞・組織",long:"正常ヒト肺線維芽細胞（normal human lung fibroblast）。HUVECと協調してフィブリンゲル内の血管モルフォゲネシス（管腔形成）をサポートするストロマ細胞。"},
  "ir":{cat:"疾患・病態",long:"インスリン抵抗性（insulin resistance）。インスリンへの感受性が低下し肝糖産生が抑制されない代謝不全状態。高insulin・高glucose・高FFAを組み合わせたIR培地でin vitroモデルに誘導できる。"},
  "g6pc":{cat:"遺伝子・タンパク質",long:"グルコース-6-ホスファターゼ触媒サブユニット（glucose-6-phosphatase catalytic subunit）。糖新生の最終酵素で、IR条件で上昇し肝糖産生増大の指標となる。"},
  "fabp1":{cat:"遺伝子・タンパク質",long:"肝型脂肪酸結合タンパク（fatty acid binding protein 1；L-FABP）。肝細胞の細胞内脂肪酸輸送に関与する。#12のIR条件ではFASNとともに変化は小さかった。"},
  "cxcl1":{cat:"シグナル・経路",long:"C-X-Cモチーフケモカインリガンド1（GROα；CXCL1）。単球・好中球を走化するケモカインで、IR肝MPS上清で増加し免疫細胞の招集に関与する。"},
  "cxcl2":{cat:"シグナル・経路",long:"C-X-Cモチーフケモカインリガンド2（GROβ；CXCL2）。CXCL1と同族の走化性ケモカインで、IR条件でCXCL1と協調して増加した。"},
  "ccl4 (mip-1β)":{cat:"シグナル・経路",long:"C-Cモチーフケモカインリガンド4（MIP-1β；CCL4）。単球・T細胞を走化するケモカインで、IR肝MPS上清で増加した。※化学傷害モデルで使う四塩化炭素CCl4（carbon tetrachloride）とは全く別物。"},
  "icam-1":{cat:"遺伝子・タンパク質",long:"細胞間接着分子1（intercellular adhesion molecule 1；CD54）。内皮炎症・白血球接着のマーカーで、IR条件の肝MPSで上昇し内皮炎症を示した。"},
  "cd163":{cat:"遺伝子・タンパク質",long:"CD163（ヘモグロビンスカベンジャー受容体）。組織定着マクロファージのマーカー。#12ではMPS内で血管外に出た単球で初期単球より上昇し、組織マクロファージ様への分化傾向を示した。#31ではiKC成熟・極性の指標、#42ではグルココルチコイド依存的に誘導される恒常性/M2マクロファージマーカーとされる。"},
  "cd14":{cat:"遺伝子・タンパク質",long:"CD14（LPS共受容体 / 単球マーカー）。単球・マクロファージのマーカーで、#12ではCD14+で単球を選別して血管腔へ添加した。"},
  "pls-da":{cat:"手法・モデル",long:"偏最小二乗判別分析（partial least squares discriminant analysis）。多変量解析手法で、#12ではサイトカイン・ケモカインパネルからIR条件と生理的条件を有意に判別した。"},
  "fibrin":{cat:"手法・モデル",long:"フィブリンゲル（fibrin hydrogel）。フィブリノゲンを重合させた天然ハイドロゲルで、HUVECによる血管形成の3D足場として機能する。"},
  "gas6":{cat:"シグナル・経路",long:"増殖停止特異的タンパク質6（growth arrest specific protein 6；GAS6）。MERTK受容体のリガンドで、生理的条件の肝MPS上清で増加し、抗炎症的な組織維持に関与する可能性が示唆された（#12）。"},
  "hipsc-hsc":{cat:"細胞・組織",long:"human iPSC-derived hepatic stellate cell（人工多能性幹細胞由来胎児型肝星細胞）。WT1/DESMIN/PDGFRβを発現し胎児HSCに近い転写プロファイルを持ち、10万倍超の増殖能を維持する。Matrigel-free多細胞オルガノイドで内皮ネットワーク形成と肝成熟を促進する。"},
  "hipsc-he":{cat:"細胞・組織",long:"human iPSC-derived hepatic endoderm（iPSC由来肝内胚葉細胞）。肝細胞前駆体として機能し、HSC共存下でHNF4A発現・アルブミン分泌・CYP450活性が向上する。Matrigel-free三細胞オルガノイドの肝成熟コンポーネント。"},
  "wt1":{cat:"遺伝子・タンパク質",long:"Wilms tumor 1（ウィルムス腫瘍タンパク1）。胎児肝星細胞（fetal HSC）の転写因子マーカーで、hiPSC-HSCがWT1陽性であることが胎児型同一性の根拠となる。"},
  "hnf4a":{cat:"遺伝子・タンパク質",long:"hepatocyte nuclear factor 4 alpha（肝細胞核内受容体4α）。肝細胞成熟の主要転写因子でALB/CYP遺伝子群の発現を制御する。Matrigel-free三細胞オルガノイドでHSC共存により発現が上昇し、HSCの肝成熟促進効果の指標となる。"},
  "rora":{cat:"遺伝子・タンパク質",long:"RAR-related orphan receptor alpha（核内受容体転写因子）。HSCの糖解/OXPHOSを抑制して静止表現型を維持する。RORA低下がHSC活性化の代謝スイッチの引き金となり、欠損マウスで線維化が増悪、アゴニストSR1078の投与で肝・心臓・腎臓の線維化が軽減した。"},
  "dihsc":{cat:"細胞・組織",long:"iPSC-differentiated hepatic stellate cell（iPSC由来肝星細胞）。Sancho-Bruらの命名で#19のhiPSC-HSCと同概念。プロテオーム軌跡解析・RORA機能解析に使用された分化誘導HSC。"},
  "oxphos":{cat:"代謝・分子",long:"oxidative phosphorylation（酸化的リン酸化）。ミトコンドリア電子伝達系によるATP産生経路。RORAが抑制することでHSCを低エネルギー・静止状態に保つ。RORA低下→OXPHOS亢進がHSC活性化の代謝的引き金となる。"},
  "sr1078":{cat:"手法・モデル",long:"SR1078（合成RORAアゴニスト）。HSC活性化の抑制・線維化の軽減を示す薬理ツールで、肝・心臓・腎臓の線維化を軽減した（#21）。"},
  "lam-like kc":{cat:"細胞・組織",long:"傷害部位でTREM2+/CD9+のLAM表現型を採用した常在クッパー細胞（KC）。単球由来の募集LAMとは発生起源が異なるが、どちらか一方にTREM2が保たれれば組織修復が成立する機能的冗長性をもつ。ヒト肝にも存在する（De Ponti et al., Immunity 2025, #22）。"},
  "proteogenomics":{cat:"手法・モデル",long:"プロテオームとトランスクリプトームを同一細胞集団で統合解析する手法。#22ではLAMとLAM様KCの分子同一性の比較に使用された。"},
  "spatial restriction":{cat:"プロセス・現象",long:"LAMとLAM様KCが傷害巣にのみ集積し健常域には少ない傷害部位特異的な分布パターン。空間トランスクリプトーム解析で可視化された。"},
  "bec":{cat:"細胞・組織",long:"biliary epithelial cell（胆管上皮細胞/胆管細胞）。胆管内腔を裏打ちする上皮細胞で、FXR–YAP軸により胆汁酸バリアを能動的に維持する。欠失でEMT→BA漏出→HSC活性化→線維化が生じる。"},
  "fxr":{cat:"遺伝子・タンパク質",long:"farnesoid X receptor（ファルネソイドX受容体）。核内受容体で胆汁酸を直接感知し、肝細胞では脂質・糖代謝を統合制御する。BECではYAPを転写活性化して胆管バリアを維持（Nat Metab 2026）。"},
  "yap":{cat:"遺伝子・タンパク質",long:"Yes-associated protein（YAP）。Hippo経路下流のトランスコアクチベーターで、TAZと対をなす。BECではFXRの転写標的として細胞接着プログラムを誘導し、密着結合を維持する（#23）。"},
  "oca":{cat:"手法・モデル",long:"obeticholic acid（オベチコール酸）。半合成FXRアゴニストで、PBC治療薬としての使用歴があり、MASHなどで臨床試験が行われた。#23ではBEC-FXR欠失マウスで線維化を悪化させ、BECのFXR状態を考慮しない全身投与が逆効果になりうることが示唆された。"},
  "plin5":{cat:"遺伝子・タンパク質",long:"perilipin 5。脂質滴（LD）表面コートタンパクのペリリピンファミリーメンバー。ミトコンドリア-LD物理的テザリングを媒介し、S155リン酸化でカップリング強度を制御（Nat Metab 2026）。"},
  "scphenomics":{cat:"手法・モデル",long:"single-cell phenomics（単一細胞フェノミクス）。共焦点組織イメージング（mtDendra2・BODIPY・ファロイジン）と深層学習セグメンテーションにより、単一細胞のミトコンドリア・脂質滴の形態特徴を門脈周囲-中心静脈軸に沿って多変量で定量する、#26で開発された手法。"},
  "mito-ld contact":{cat:"プロセス・現象",long:"mitochondria–lipid droplet contact site（ミトコンドリア-脂質滴コンタクト部位）。ミトコンドリアと脂質滴が物理的に接触する部位で、FFAのエステル化・LDへのTG貯蔵を促進して脂肪毒性を緩和する方向に働くことが示された（脂肪酸輸送の方向自体は未測定）。絶食で増加、短期WDで減少、長期WDでは再び増加し、PLIN5 S155のリン酸化に依存して調節される。"},
  "lipotoxicity":{cat:"疾患・病態",long:"lipotoxicity（脂質毒性）。#43では脂肪酸そのものが細胞を傷害する作用で、脂肪の蓄積とは別の現象とされる。#26では細胞内LDの過剰蓄積に伴うER stress・ミトコンドリア機能障害・アポトーシスを指し、MASLD→MASH進行に中心的な役割を担う。WDマウスでPLIN5 S155A過剰発現は脂肪毒性を軽減した。"},
  "visium hd":{cat:"手法・モデル",long:"10x Genomics Visium HD。2 μm×2 μmのビンで解析する高解像度の空間トランスクリプトームで、従来のVisiumより高解像度（Yakubovsky 2026, #24）。"},
  "phenocycler":{cat:"手法・モデル",long:"Akoya Biosciences PhenoCycler-Fusion。蛍光抗体の染色サイクルを繰り返して同一切片上で多数のタンパク質を可視化する高多重免疫蛍光イメージャー（#24では48マーカー）。"},
  "ep300":{cat:"遺伝子・タンパク質",long:"E1A binding protein p300。ヒストンアセチルトランスフェラーゼ型コアクチベーター。TET1（Zone1/periportal）またはHIF1α（Zone3/pericentral）と複合体を形成しゾーン特異遺伝子を活性化（#25 Takebe Nature 2025）。"},
  "tet1":{cat:"遺伝子・タンパク質",long:"ten-eleven translocation methylcytosine dioxygenase 1。DNA脱メチル化酵素。アスコルビン酸条件下でEP300と結合してZone1（門脈周囲）プログラムを確立する（#25）。"},
  "porto-central axis":{cat:"細胞・組織",long:"門脈-中心静脈軸（porto-central axis）。肝小葉内の門脈域（Zone 1, 高O2）から中心静脈（Zone 3, 低O2）へ向かうzonation軸。酸素・栄養・BA濃度勾配の構造的基盤。ヒトではマウスより中心静脈側シフト（#24）。"},
  /* ===== KC/LSEC/HSC/マーカー群（No.27-42）の新規用語 ===== */
  "id3":{cat:"遺伝子・タンパク質",long:"inhibitor of DNA binding 3（DNA結合阻害因子3）。肝細胞との接触が単球に誘導するKC同一性因子で、流入単球のKC化に必要。Bonnardel 2019（#27）で同定。"},
  "lxrα":{cat:"遺伝子・タンパク質",long:"liver X receptor alpha（肝X受容体α；NR1H3）。LSEC由来のDLL4–Notchが誘導し、HSC由来と推定されるBMP9がNotchと相乗して増強する、KC成熟の鍵となる核内受容体。BMP–Notch下流でKC同一性を確立する。Bonnardel 2019（#27）で同定。"},
  "dll4":{cat:"遺伝子・タンパク質",long:"Delta-like ligand 4。LSEC/HSCが提示するNotchリガンドで、Notchを介してLXRαを誘導しKC同一性プログラムを起動する（Bonnardel 2019, #27）。"},
  "bmp9":{cat:"シグナル・経路",long:"bone morphogenetic protein 9（GDF2）。#27ではHSC由来と推定されるBMPリガンドで、Notchと相乗してKC同一性プログラムを増強する。#32（総説）ではHSC由来の循環因子として、BMP9 KOマウスでLSEC終末分化マーカー（LYVE-1・Stab2等）が低下しfenestraeが減少したという引用データが紹介されている（ヒト肝での検証は示されていない）。"},
  "lyve-1":{cat:"遺伝子・タンパク質",long:"lymphatic vessel endothelial hyaluronan receptor 1（LYVE1）。健常LSECのマーカーで、#32（総説）が引用するBMP9 KOマウスで発現が低下したと紹介されている。"},
  "stab2":{cat:"遺伝子・タンパク質",long:"stabilin-2（FEEL-2）。LSEC同一性マーカー兼スカベンジャー受容体で、#32（総説）が引用するBMP9 KOマウスで低下したと紹介されている。"},
  "vsig4":{cat:"遺伝子・タンパク質",long:"V-set and immunoglobulin domain-containing protein 4（VSIG4；別名CRIg）。KC/マクロファージの補体受容体で、常在KCマーカー。#40ではPI3K/Akt経路でPDK2を誘導し、ピルビン酸酸化の低下とmtROS産生の抑制を介してLPS誘発炎症を抑える。#31ではiKC成熟の指標とされる（Li 2017, #40；Tasnim 2019, #31）。"},
  "cd206":{cat:"遺伝子・タンパク質",long:"CD206（マンノース受容体；MRC1）。M2マクロファージのマーカーで、グルココルチコイド（GR）依存的に誘導される修復型表現型の指標（Desgeorges 2019, #41；Heideveld 2018, #42）。"},
  "endmt":{cat:"プロセス・現象",long:"endothelial-to-mesenchymal transition（内皮–間葉転換）。LSECが内皮機能を失い間葉様の性質を獲得する過程。capillarizedなLSECが部分的なEndMTを起こして、コラーゲン等のECM成分を過剰産生し線維化を促進するとの報告がある（Qu 2024, #35）。"},
  "lanifibranor":{cat:"手法・モデル",long:"IVA337。PPARα/δ/γを活性化するパンPPARアゴニスト。#34のヒト生検（NATIVE試験）では周門脈域CD34の改善例を増やし小葉域の悪化を減らしたが、CD34陽性血管密度自体は変えなかった。門脈圧・肝内血管抵抗の正常化はラットMASLDモデルでの結果（Rautou 2025, #34）。"},
  "pdk2":{cat:"遺伝子・タンパク質",long:"pyruvate dehydrogenase kinase 2。解糖系・ピルビン酸代謝を調節するキナーゼ。VSIG4→PI3K/Akt軸の下流で誘導され、ピルビン酸→アセチルCoA変換の低下とmtROS産生の抑制を介してマクロファージの炎症を抑える（Li 2017, #40）。"},
  "rxra":{cat:"遺伝子・タンパク質",long:"retinoid X receptor alpha（レチノイドX受容体α）。核内受容体RXRファミリーのαサブタイプ。同ファミリーのRXRGは#53でPC LSECのFGF1転写に関わる。"},
  "fosl1":{cat:"遺伝子・タンパク質",long:"FOS-like antigen 1（Fra-1）。AP-1ファミリーの転写因子。#39ではAP-1/JUNBが活性化HSCの系列決定因子として議論されており、FOSL1はその文脈で挙げられる（Kisseleva 2025, #39）。"},
  "dexamethasone":{cat:"手法・モデル",long:"デキサメタゾン（合成グルココルチコイド）。GRを介してCD163・CD206の発現を誘導し、単球/マクロファージを抗炎症・修復型の表現型へ向かわせる。#41ではKC/iKCの成熟評価でCD163を指標とする根拠・培養条件の設計の参考とされ、#42ではGR依存的（RU486で低下）にCD163+CD206+マクロファージを誘導する培地に含まれた。#18ではOSM・HGFと併用してHEP分化に用いられた。"},
  "ikc":{cat:"細胞・組織",long:"iPSC-derived Kupffer cell（iPSC由来クッパー細胞様細胞）。#31では、肝細胞との直接接触が成熟に必須とされ、共培養下でVSIG4・CD163・TIMD4・LXRα・ID3を発現し、貪食能やIL-6/TNFα分泌を獲得した。#48のLEADSではKC構成要素として用いられた（Tasnim 2019のプロトコル由来）。"},
  "emp":{cat:"細胞・組織",long:"erythro-myeloid progenitor（赤血球骨髄系前駆細胞）。卵黄嚢由来の前駆細胞で、多くの組織常在マクロファージの起源とされる（#30）。"},
  "gr":{cat:"遺伝子・タンパク質",long:"glucocorticoid receptor（グルココルチコイド受容体；NR3C1）。デキサメタゾン等のGCが結合する核内受容体で、CD163・CD206の誘導を媒介する。GR拮抗薬RU486（mifepristone）でCD163誘導が低下し、GR依存的であることが示された（#41, #42）。"},
  "decm":{cat:"手法・モデル",long:"decellularized extracellular matrix（脱細胞化細胞外マトリックス）。臓器から細胞を除いて残した天然の足場で、血管・実質の空間配置を再建する土台に使う（Kim 2026, #49）。"},
  "vca":{cat:"手法・モデル",long:"vascular coating agent（血管コーティング剤）。抗CD31アプタマーを使い内皮細胞を足場の血管位置へ誘導する被覆材。血管と実質の空間的協調を助ける（Kim 2026, #49）。"},
  "igf2":{cat:"遺伝子・タンパク質",long:"insulin-like growth factor 2。IGF1R-AKT/MAPK軸を駆動して肝オルガノイドの空間構築と機能成熟を支える増殖因子。外因性添加で治療成績が向上した（Kim 2026, #49）。"},
  "igf1r":{cat:"遺伝子・タンパク質",long:"IGF1 receptor（IGF1受容体）。IGF2を受けてAKT/MAPKを活性化し、血管化肝オルガノイドの組織化の鍵となる受容体（Kim 2026, #49）。"},
  "phli-seq":{cat:"手法・モデル",long:"phenotype-based high-throughput laser-aided isolation sequencing。組織切片から表現型と位置で小領域を切り出して全長RNAを読む空間トランスクリプトームで、#49では実質と血管を別々に解析してIGF2軸の同定に用いられた（Kim 2026, #49）。"},
  "lgr5":{cat:"遺伝子・タンパク質",long:"leucine-rich repeat-containing GPCR 5。肝幹/前駆細胞マーカー。#49ではTAA誘発慢性肝不全マウスへの移植後に、血管周囲でLGR5陽性細胞が動員された（Kim 2026, #49）。"},
  "hepatoblast":{cat:"細胞・組織",long:"肝芽細胞。肝細胞と胆管上皮に分化できる胎児肝の前駆細胞。iPSC由来肝オルガノイドの実質側の出発細胞（Kim 2026, #49）。"},
  "lsec":{cat:"細胞・組織",long:"liver sinusoidal endothelial cell（肝類洞内皮細胞）。有窓構造でNOを出しHSCを静止に保つが、毛細血管化すると線維化を促す。c-Kit勾配でPC〜PPに階層化される（#50, #53, #54）。"},
  "fbxw7":{cat:"遺伝子・タンパク質",long:"F-box and WD repeat domain-containing 7。NOTCH1等を分解するE3ユビキチンリガーゼで、LSECでは線維化のブレーキ。欠損でN1ICDが安定化する（Yan 2026, #50）。"},
  "notch1":{cat:"シグナル・経路",long:"notch receptor 1。切断で生じたN1ICDが核でRBPJと転写を駆動する。LSECで過剰だと毛細血管化・線維化を促す（Yan 2026, #50）。"},
  "n1icd":{cat:"遺伝子・タンパク質",long:"NOTCH1 intracellular domain（NOTCH1細胞内ドメイン）。NOTCH1の活性型で、FBXW7が分解する標的。安定化するとSEMA3G転写が高まる（Yan 2026, #50）。"},
  "sema3g":{cat:"遺伝子・タンパク質",long:"semaphorin 3G。FBXW7欠損LSECで最も上がる分泌因子で、HSCのNRP2を介して線維化を促すパラクリン因子（Yan 2026, #50）。"},
  "rbpj":{cat:"遺伝子・タンパク質",long:"recombination signal binding protein for Ig kappa J region。N1ICDと複合体を作りNotch標的（SEMA3G等）を転写する中核因子（Yan 2026, #50）。"},
  "nrp2":{cat:"遺伝子・タンパク質",long:"neuropilin 2。HSC側のSEMA3G受容体で、LSEC由来の線維化シグナルの受け手（Yan 2026, #50）。"},
  "samac":{cat:"細胞・組織",long:"scar-associated macrophage（瘢痕関連マクロファージ；TREM2+）。慢性肝疾患で線維化ニッチに集まる疾患拡大マクロファージ。OLR1+の炎症性亜集団を含む（Ramachandran 2026, #51）。"},
  "olr1":{cat:"遺伝子・タンパク質",long:"oxidized LDL receptor 1（LOX-1）。炎症性SAMacが発現するスカベンジャー受容体。高発現は複数の病因で線維化の強さと相関し、MASLDでは不良な転帰と関連する。治療標的候補（Ramachandran 2026, #51）。"},
  "cld":{cat:"疾患・病態",long:"chronic liver disease（慢性肝疾患）。各種病因で線維化が進み予後を悪化させる病態の総称。単一細胞アトラスの対象（Ramachandran 2026, #51）。"},
  "single-cell atlas":{cat:"手法・モデル",long:"多数の検体から単一細胞レベルで細胞状態を網羅した参照地図。本研究では健常・CLD由来64.9万細胞で125状態を解像（Ramachandran 2026, #51）。"},
  "kat5":{cat:"遺伝子・タンパク質",long:"lysine acetyltransferase 5（TIP60）。ACSS2と複合体を作り、ヒストンのクロトニル化を介してAIF1転写を上げ炎症を駆動する（Wen 2026, #52）。"},
  "aif1":{cat:"遺伝子・タンパク質",long:"allograft inflammatory factor 1。ACSS2-KAT5がヒストンクロトニル化で誘導する標的で、肝炎症と肝細胞老化を促しMASH化を進める（Wen 2026, #52）。"},
  "histone crotonylation":{cat:"プロセス・現象",long:"ヒストンのリジンがクロトニル基で修飾されるエピジェネティック修飾。ACSS2-KAT5がこれを介して炎症遺伝子（AIF1）を活性化する（Wen 2026, #52）。"},
  "navitoclax":{cat:"手法・モデル",long:"BCL-2/BCL-xL阻害薬（ABT-263）。老化細胞を除くセノリティクスで、MCD食下でのACSS2過剰発現による病態を反転した（Wen 2026, #52）。"},
  "hffd":{cat:"手法・モデル",long:"high-fat high-fructose diet（高脂肪高フルクトース食）。MASLD/MASHを誘導するマウス食餌モデル（Wen 2026, #52）。"},
  "rxrg":{cat:"遺伝子・タンパク質",long:"retinoid X receptor gamma（レチノイドX受容体γ）。PC LSECでFGF1の転写を駆動する核内受容体。レチノイン酸がリガンド（Fang 2026, #53）。"},
  "ra":{cat:"代謝・分子",long:"retinoic acid（レチノイン酸）。ビタミンAの活性代謝物でRXRのリガンド。LSEC由来FGF1軸を強め脂肪化を抑える（Fang 2026, #53）。"},
  "fgf1":{cat:"遺伝子・タンパク質",long:"fibroblast growth factor 1。PC LSECがRXRG依存で分泌し、肝細胞のFGFR4を介して脂質蓄積を抑える抗脂肪化因子（Fang 2026, #53）。"},
  "fgfr4":{cat:"遺伝子・タンパク質",long:"fibroblast growth factor receptor 4。肝細胞側のFGF1受容体で、脂質蓄積の抑制シグナルを受ける（Fang 2026, #53）。"},
  "bodipy":{cat:"手法・モデル",long:"boron-dipyrromethene。中性脂質を染める蛍光色素で、脂肪滴の空間分布を可視化する（Fang 2026, #53）。"},
  "shear stress":{cat:"プロセス・現象",long:"haemodynamic shear stress（ずり応力）。血流が血管壁に与える力。LSECがこれをセンスしてアンギオクリンWntを調節する（Lee 2026, #54）。"},
  "wnt2":{cat:"遺伝子・タンパク質",long:"Wnt family member 2。PC LSECが出すアンギオクリンWntリガンドで、肝細胞のβ-catenin標的/GSを支える（Lee 2026, #54）。"},
  "wnt9b":{cat:"遺伝子・タンパク質",long:"Wnt family member 9b。PC LSEC由来のWntリガンド。Wnt2と並び肝zonationを維持する（Lee 2026, #54）。"},
  "fzd4":{cat:"遺伝子・タンパク質",long:"frizzled class receptor 4。Wnt受容体で、LSEC自身がWntを受けるオートクリン系の一員。免疫染色では小葉軸にほぼ均一に発現する（偏りが明確なのはLRP6）（Lee 2026, #54）。"},
  "lrp6":{cat:"遺伝子・タンパク質",long:"LDL receptor related protein 6。Wntの共受容体で、免疫染色で中心静脈側LSECに偏り、PC LSECがWntを受ける準備状態にあることを示す。FZDと組んでβ-cateninシグナルを起動する（Lee 2026, #54）。"},
  "double-iecko":{cat:"手法・モデル",long:"内皮でWnt分泌のカーゴ受容体Wls（Wntless）とWnt増強因子Rspo3を誘導型に二重欠損させたマウス（Wnt受容体やWntリガンド遺伝子そのものの欠損ではない）。GSが失われ、肝のzonationが崩れる（Lee 2026, #54）。"},
  "cx37":{cat:"遺伝子・タンパク質",long:"connexin 37（GJA4）。血管Wntがオートクリンに制御するギャップ結合分子で、LSEC間の連絡を担う。Wnt欠損で低下する（Lee 2026, #54）。"},
  "cx43":{cat:"遺伝子・タンパク質",long:"connexin 43（GJA1）。ギャップ結合分子で、血管Wntに調節されWnt欠損で低下し、LSECのカルシウム伝播に関わる（Lee 2026, #54）。"},
  "gs":{cat:"遺伝子・タンパク質",long:"glutamine synthetase（Glul）。PC肝細胞のzonationマーカーで、アンギオクリンWntに依存して発現する（Lee 2026, #54）。"},
  "liv2trans":{cat:"手法・モデル",long:"Latent In Vitro to In Vivo Translation。ヒト肝生検データをMPSのPC空間に射影・逆射影したときのPLSR予測性能の損失から翻訳性を測り、上げる実験条件を提案する機械学習枠組み（Cadavid 2026, #55）。"},
  "translatability":{cat:"プロセス・現象",long:"in vitroの結果がヒト（in vivo）をどれだけ予測できるかの度合い。LIV2TRANSが定量化の対象とする（Cadavid 2026, #55）。"},
  "plsr/pca":{cat:"手法・モデル",long:"partial least squares regression / principal component analysis。PLSRは遺伝子発現から組織学スコアを少数の潜在変数で予測する回帰、PCAはMPSの発現空間を主成分で表す手法。ヒトデータをMPSのPC空間に通して予測性能の損失を測る（Cadavid 2026, #55）。"},
  "jak":{cat:"シグナル・経路",long:"Janus kinase（ヤヌスキナーゼ）。サイトカイン受容体に結合してSTATをリン酸化するキナーゼ。IFNシグナルの中核で、摂動がMPS翻訳性を上げうる（Cadavid 2026, #55）。"},
  "stat":{cat:"遺伝子・タンパク質",long:"signal transducer and activator of transcription。JAKで活性化し核へ移る転写因子。JAK-STAT摂動が予測性能を上げうる（Cadavid 2026, #55）。"},
  "interferon":{cat:"シグナル・経路",long:"interferon（IFN）。JAK-STATを介する炎症/抗ウイルスサイトカイン。IFN-αはTGFβ1誘導の表現型に拮抗し、MPSの翻訳性を上げる追加キューとして提案・検証された（Cadavid 2026, #55）。"},
  "easyscp":{cat:"手法・モデル",long:"EasySCP（略称の展開は原著に記載なし）。FACS分取＋384ウェル1ステップ消化＋高感度MSを統合した高スループット単一細胞プロテオミクス法（Hao 2026, #56）。"},
  "scp":{cat:"手法・モデル",long:"single-cell proteomics（単一細胞プロテオミクス）。単一細胞のタンパク質を網羅測定する手法。従来は工程が複雑で普及が限られていた（Hao 2026, #56）。"},
  "hss":{cat:"手法・モデル",long:"hepatocyte spatial status score。458の保存zonationマーカーから選んだ215の差次的タンパク質（中心静脈側147・門脈側68）の2遺伝子セットのGSVAスコア差で、肝細胞のゾーン座標を推定・再構成するスコア（Hao 2026, #56）。"},
  "dia":{cat:"手法・モデル",long:"data-independent acquisition。全イオンを網羅的に断片化して定量する質量分析モードで、微量試料でも再現性が高い（Hao 2026, #56）。"},
  "facs":{cat:"手法・モデル",long:"fluorescence-activated cell sorting。蛍光で細胞を1個ずつ分取する手法で、単一細胞解析の入力を作る（Hao 2026, #56）。"},
  "zonation marker":{cat:"手法・モデル",long:"5つのデータセットで一貫してゾーン依存性を示した458タンパク質（保存zonationマーカー）。そこから選んだ215個がHSSなどゾーン座標推定の土台になる（Hao 2026, #56）。"},
  "senolytics":{cat:"手法・モデル",long:"老化細胞を選択的に死滅させる薬剤。D+Q等があり、線維化・炎症の軽減を狙う（Koning 2026, #57）。"},
  "d+q":{cat:"手法・モデル",long:"dasatinib plus quercetin。ダサチニブ（キナーゼ阻害）＋ケルセチン（フラボノイド）の併用セノリティクス。間欠投与する（Koning 2026, #57）。"},
  "senescence":{cat:"プロセス・現象",long:"cellular senescence（細胞老化）。分裂を止めたままSASPを出し続ける細胞状態で、肝の炎症・線維化を駆動する（Koning 2026, #57; Wen 2026, #52）。"},
  "mash":{cat:"疾患・病態",long:"metabolic dysfunction-associated steatohepatitis。脂肪化に炎症・肝細胞障害・線維化が重なった病態で、線維化進行で予後が悪化する（#52, #57, #58）。"},
  "nas":{cat:"手法・モデル",long:"NAFLD activity score。脂肪化・小葉炎症・肝細胞風船様変性の合計スコアで、MASHの活動性指標（Koning 2026, #57）。"},
  "fibrosis stage":{cat:"疾患・病態",long:"肝線維化の進行度（F0〜F4）。1段階以上の改善がセノリティクス試験の主要評価項目（Koning 2026, #57）。"},
  "trnp1":{cat:"遺伝子・タンパク質",long:"TMF1-regulated nuclear protein 1。脾CD8 T細胞でメチル基不足に伴うクロマチン再編により立ち上がる転写因子で、FURIN/CTSDを誘導しINSR-α分泌を促す（Zhang 2026, #58）。"},
  "insr-α":{cat:"遺伝子・タンパク質",long:"insulin receptor alpha subunit（インスリン受容体α鎖）。TRNP1+ CD8 T細胞が分泌する線維化促進因子で、HSCを活性化する。中和が治療標的（Zhang 2026, #58）。"},
  "furin":{cat:"遺伝子・タンパク質",long:"furin（プロタンパク質転換酵素）。TRNP1に誘導され、pro-INSRをα鎖とβ鎖に切断して成熟させ細胞膜への輸送を促す（エクトドメインの切り出しはCTSDが担う）（Zhang 2026, #58）。"},
  "ctsd":{cat:"遺伝子・タンパク質",long:"cathepsin D（カテプシンD）。アスパラギン酸プロテアーゼで、TRNP1に誘導され膜上INSRのエクトドメイン・シェディング（INSR-αの切り出し・分泌）を担う（Zhang 2026, #58）。"},
  "cd8 t cell":{cat:"細胞・組織",long:"CD8+ T細胞（細胞傷害性T細胞）。脾臓で再プログラムされ、線維化促進性のTRNP1+サブセットになる（Zhang 2026, #58）。"},
  "h3k27ac":{cat:"プロセス・現象",long:"histone H3 lysine 27 acetylation。活性型エンハンサー/プロモーターの印で、増加がTRNP1発現の立ち上げに寄与する（Zhang 2026, #58）。"},
  "h3k27me3":{cat:"プロセス・現象",long:"histone H3 lysine 27 trimethylation。抑制性のヒストン修飾。MASLD/MASHの脾CD8 T細胞では全体的に脱メチル化（低下）してTRNP1プロモーターの抑制が解除される（H3K9me3は変化しない）（Zhang 2026, #58）。"},
  "tad":{cat:"プロセス・現象",long:"topologically associating domain。クロマチンが会合する空間ドメインで、再編によりエンハンサー-プロモーター接触が変わる（Zhang 2026, #58）。"},
  "ersodetug":{cat:"手法・モデル",long:"ersodetug（RZ358）。低血糖症の治療用に開発されたINSR標的モノクローナル抗体。INSR中和抗体(BE0338)とは別の薬剤で、どちらもin vivo投与でMASLD/MASH誘発の肝線維化を軽減した（Zhang 2026, #58）。"},
  /* ===== 追加：check.mjs の警告に出た用語（No.09–42） ===== */
  "wnt / wnt":{cat:"シグナル・経路",long:"Wingless-related integration site（Wnt）リガンドが起動するシグナル経路。発生・幹細胞・肝代謝を制御する分泌型リガンドファミリーで、WNT/βカテニンシグナルを介して肝細胞のzonationや再生に関わる。HSCに豊富なRSPO3がLGR4/5受容体を介してWntシグナルを増強する（#09）。"},
  "masld":{cat:"疾患・病態",long:"metabolic dysfunction-associated steatotic liver disease（代謝機能障害関連脂肪性肝疾患）。#17では老化肝細胞が蓄積して進行に寄与するとされ、SHGSが進行・退縮に一致して変動した。"},
  "timd4":{cat:"遺伝子・タンパク質",long:"T cell immunoglobulin and mucin domain 4（TIM4タンパクの遺伝子）。常在KC特異的なマーカー遺伝子でefferocytosis受容体。#22ではKCのマーカーとして、#31ではiKC成熟の指標として用いられた。"},
  "ba":{cat:"代謝・分子",long:"bile acid（胆汁酸）。コレステロール由来の両親媒性ステロイドで、FXRリガンドとして代謝制御に関与する。#23ではBECのバリアが破れて過剰に漏出・蓄積するとHSC活性化・線維化が生じる。"},
  "β-catenin":{cat:"遺伝子・タンパク質",long:"β-catenin（CTNNB1）。Wntシグナルの核トランスロケーター。#23ではBEC-FXR/YAP欠失で活性化し、EMTと増殖を駆動する。Wnt/βカテニン経路としての役割は#09の「β-catenin (ctnnb1)」も参照。"},
  "hif1α":{cat:"遺伝子・タンパク質",long:"hypoxia-inducible factor 1α。低酸素応答転写因子。ビリルビン富化環境でEP300と協働してZone3（中心静脈周囲）プログラムを確立する（#25）。"},
  "hipsc":{cat:"細胞・組織",long:"human induced pluripotent stem cell（ヒト人工多能性幹細胞）。#25ではゾーン特異的肝オルガノイド（mZ-HLO）の出発細胞として用いられた。"},
  "wd":{cat:"手法・モデル",long:"Western diet（西洋食）。高脂肪・高糖の肥満誘導食。#26では4週投与で単純性脂肪化とmito-LDコンタクトの減少を、12週投与ではコンタクトの増加を示す条件として用いられた。"},
  "kc niche":{cat:"細胞・組織",long:"Kupffer cell niche。肝細胞・LSEC・HSCが構成する、KC同一性を維持する微小環境（Bonnardel 2019, #27）。"},
  "bmp":{cat:"シグナル・経路",long:"bone morphogenetic protein。ニッチ細胞由来のシグナルで、Notchと協働してLXRα経由でKC化を促進する（#27）。"},
  "reskc":{cat:"細胞・組織",long:"resident Kupffer cell（常在クッパー細胞）。胚由来・自己複製性で、恒常性・寛容性機能を担う。MASLD進行で減少し、単球由来集団に置換される（#28）。"},
  "niche simplification":{cat:"プロセス・現象",long:"単一KC集団のみを入れる培養系で、肝マクロファージの多様性が失われること（#28）。"},
  "metabolic gatekeeper":{cat:"プロセス・現象",long:"代謝産物（胆汁酸・脂肪酸）のセンシング・処理を担うKCの機能的役割。KCを肝の恒常性と代謝の門番として位置づける概念（#29）。"},
  "tolerogenic":{cat:"プロセス・現象",long:"tolerogenic（寛容原性）。恒常状態のKCがもつ免疫抑制的・寛容性の性質で、MASLDでは炎症促進性へ変質することが病態進行の分岐点とされる（#29）。"},
  "tissue residency":{cat:"プロセス・現象",long:"組織常在性。KCが胚由来で、自己複製により組織内で維持される性質（#29）。"},
  "capsular macrophage":{cat:"細胞・組織",long:"capsular macrophage（被膜下マクロファージ）。肝被膜に居住し、腹腔から肝へ入る細菌の捕捉に関わるマクロファージ集団。単球由来で生後に確立される（#30）。"},
  "yolk sac":{cat:"細胞・組織",long:"yolk sac（卵黄嚢）。胚発生初期の造血部位で、KC等の組織常在マクロファージの発生起源（#30）。"},
  "bioreactivity":{cat:"プロセス・現象",long:"総説が扱う、LSECを含む肝モデルの薬物感受性（drug-sensitive）応答性。3Dヒト肝モデルでの薬物毒性評価に関連する（#33）。"},
  "immune tolerance":{cat:"プロセス・現象",long:"immune tolerance（免疫寛容）。健常LSECが担う寛容維持機能で、疾患では炎症促進性へ転換する（#33）。"},
  "ppar":{cat:"遺伝子・タンパク質",long:"peroxisome proliferator-activated receptor。脂質代謝・抗線維化に関わる核内受容体で、lanifibranorの標的（#34）。"},
  "gatekeeper":{cat:"プロセス・現象",long:"LSEC gatekeeper function。健常LSECがHSC静止維持・物質輸送を担う門番的機能で、脱分化・capillarizationで失われる（#35の総説は「HSC静止維持能の喪失」と記述）。"},
  "tgf-β/smad":{cat:"シグナル・経路",long:"TGF-β/Smad signaling。HSC活性化の中心経路で、Smad2/3を介してECM産生を誘導する（#36）。"},
  "yap-taz":{cat:"遺伝子・タンパク質",long:"YAP/TAZ（Hippo経路のエフェクター）。機械刺激・硬さ応答でHSC活性化を促す転写コアクチベーターで、#36が取り上げる六経路には含まれない。"},
  "rspo3":{cat:"遺伝子・タンパク質",long:"R-spondin 3。HSCが産生してWntシグナルを増強する因子で、肝zonation・恒常性を支持する（#37）。#09ではHSC選択的なRspo3欠損でzonation・肝臓サイズ・再生・CYP450依存の解毒能が変化してALD・MASLDが悪化し、RSPO3発現はHSC活性化とともに低下した。"},
  "myofibroblast":{cat:"細胞・組織",long:"myofibroblast（筋線維芽細胞）。活性化HSCが転換する、完全活性化したECM産生性の線維化産生細胞（#37, #39）。"},
  "tlr4-nf-κb":{cat:"シグナル・経路",long:"TLR4 / NF-κB signaling。LPSで活性化される炎症経路で、HSC-マクロファージのクロストークと線維化に寄与する（#38）。"},
  "jak-stat":{cat:"シグナル・経路",long:"JAK-STAT signaling。サイトカイン応答経路で、HSC-マクロファージ自己増幅ループの一軸（#38）。"},
  "pdgf":{cat:"シグナル・経路",long:"platelet-derived growth factor。マクロファージ由来のHSC増殖・活性化因子（#38）。"},
  "self-amplifying loop":{cat:"プロセス・現象",long:"HSC–macrophage self-amplifying loop。HSCとマクロファージが互いを活性化し続ける正のフィードバック回路（#38）。"},
  "initiatory hsc":{cat:"細胞・組織",long:"initiatory hepatic stellate cell。静止期と筋線維芽細胞の中間にある活性化初期のHSC状態で、#39の総説では中間活性化（A2）クラスターとして記述される。"},
  "metabolic reprogramming":{cat:"プロセス・現象",long:"活性化に伴う酸化的リン酸化から解糖への切り替えと、グルタミン分解・de novo lipogenesis・乳酸産生の亢進（#39）。"},
  "crig":{cat:"遺伝子・タンパク質",long:"complement receptor of the immunoglobulin superfamily。VSIG4の別名で、補体オプソニン化粒子の貪食受容体（#40）。"},
  "glucocorticoid":{cat:"代謝・分子",long:"glucocorticoid（GC）。GRを介してマクロファージを抗炎症/修復型の表現型（CD163/CD206の発現上昇など）へ向かわせるステロイド（#41）。#42ではヒト単球をCD163+CD206+のM2様マクロファージへ分化誘導した。"},
  "erythroblastic island mφ":{cat:"細胞・組織",long:"erythroblastic island macrophage（赤芽球島マクロファージ）。赤芽球を支持する貪食型マクロファージで、#42のGC誘導マクロファージが類似する。"},
  "cd169":{cat:"遺伝子・タンパク質",long:"sialoadhesin（SIGLEC1）。組織常在・貪食型マクロファージのマーカー。#42ではタンパク発現はGC非依存的で、mRNAのみGR依存的に増加した。#08の輸注細胞でも高発現していた。"},
  "ru486":{cat:"手法・モデル",long:"mifepristone（GR拮抗薬）。GRを阻害し、GC依存的なCD163誘導を低下させる薬理ツール（#42）。"},
};
